/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface FoundationGesture {
  authorUserId: string | null;
  id: string;
  name: string;
  outcome: string;
  receivedAt: Generated<Timestamp>;
  response: Json;
  workstationId: string | null;
}

export interface FoundationRole {
  id: Generated<string>;
  name: string;
  nature: string;
}

export interface FoundationRolePermission {
  permission: string;
  roleId: string;
}

export interface FoundationSession {
  expiresAt: Timestamp;
  id: Generated<string>;
  revoked: Generated<boolean>;
  tokenHash: Buffer;
  userId: string;
}

export interface FoundationSite {
  code: string;
  id: Generated<string>;
  name: string;
  timeZone: string;
}

export interface FoundationTraceEvent {
  authorUserId: string | null;
  data: Generated<Json>;
  decisionTrace: Json | null;
  gestureId: string | null;
  id: Generated<string>;
  occurredAt: Generated<Timestamp>;
  origin: string | null;
  originAt: Timestamp | null;
  type: string;
  workstationId: string | null;
}

export interface FoundationTraceEventObject {
  eventId: string;
  objectId: string;
  objectType: string;
  occurredAt: Timestamp;
}

export interface FoundationUser {
  active: Generated<boolean>;
  displayName: string;
  id: Generated<string>;
  loginName: string;
  passwordHash: string;
}

export interface FoundationUserRole {
  roleId: string;
  userId: string;
}

export interface FoundationUserSite {
  execution: Generated<boolean>;
  siteId: string;
  userId: string;
}

export interface FoundationWorkstation {
  id: Generated<string>;
  name: string;
  revoked: Generated<boolean>;
  siteId: string;
}

export interface DB {
  "foundation.gesture": FoundationGesture;
  "foundation.role": FoundationRole;
  "foundation.rolePermission": FoundationRolePermission;
  "foundation.session": FoundationSession;
  "foundation.site": FoundationSite;
  "foundation.traceEvent": FoundationTraceEvent;
  "foundation.traceEventObject": FoundationTraceEventObject;
  "foundation.user": FoundationUser;
  "foundation.userRole": FoundationUserRole;
  "foundation.userSite": FoundationUserSite;
  "foundation.workstation": FoundationWorkstation;
}
