/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface FoundationGesture {
  authorUserId: string | null;
  id: string;
  name: string;
  outcome: string;
  receivedAt: Generated<Timestamp>;
  response: Json;
  workstationId: string | null;
}

export interface FoundationNumberingCounter {
  nextValue: Int8;
  objectType: string;
  partitionKey: string;
}

export interface FoundationNumberingScheme {
  objectType: string;
  segments: Json;
}

export interface FoundationProvider {
  name: string | null;
  singleton: Generated<boolean>;
}

export interface FoundationRole {
  id: Generated<string>;
  name: string;
  nature: string;
  template: string | null;
}

export interface FoundationRolePermission {
  permission: string;
  roleId: string;
}

export interface FoundationSession {
  expiresAt: Timestamp;
  id: Generated<string>;
  revoked: Generated<boolean>;
  tokenHash: Buffer;
  userId: string;
}

export interface FoundationSite {
  active: Generated<boolean>;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  code: string;
  countryCode: Generated<string>;
  id: Generated<string>;
  name: string;
  postalCode: string | null;
  snapshotTime: Generated<string>;
  timeZone: string;
}

export interface FoundationSiteClosure {
  day: string;
  kind: string;
  label: string;
  siteId: string;
}

export interface FoundationSiteOpeningRange {
  closesAt: string;
  opensAt: string;
  siteId: string;
  weekday: number;
}

export interface FoundationTeam {
  active: Generated<boolean>;
  id: Generated<string>;
  leadUserId: string | null;
  name: string;
  siteId: string;
}

export interface FoundationTeamMember {
  teamId: string;
  userId: string;
}

export interface FoundationTraceEvent {
  authorUserId: string | null;
  data: Generated<Json>;
  decisionTrace: Json | null;
  gestureId: string | null;
  id: Generated<string>;
  occurredAt: Generated<Timestamp>;
  origin: string | null;
  originAt: Timestamp | null;
  teamId: string | null;
  type: string;
  workstationId: string | null;
}

export interface FoundationTraceEventObject {
  eventId: string;
  objectId: string;
  objectType: string;
  occurredAt: Timestamp;
}

export interface FoundationUser {
  active: Generated<boolean>;
  displayName: string;
  email: string | null;
  id: Generated<string>;
  language: Generated<string>;
  loginName: string;
  passwordHash: string;
  reportsToUserId: string | null;
}

export interface FoundationUserRole {
  roleId: string;
  userId: string;
}

export interface FoundationUserSite {
  execution: Generated<boolean>;
  siteId: string;
  userId: string;
}

export interface FoundationWorkstation {
  id: Generated<string>;
  name: string;
  revoked: Generated<boolean>;
  siteId: string;
}

export interface LogisticsBatch {
  expiryDate: string | null;
  id: Generated<string>;
  itemId: string;
  manufacturingDate: string | null;
  number: string;
}

export interface LogisticsCarrierAccount {
  accountNumber: string;
  active: Generated<boolean>;
  carrierId: string;
  contractReference: string | null;
  id: Generated<string>;
  principalId: string | null;
}

export interface LogisticsCarrierService {
  acceptsDangerousGoods: Generated<boolean>;
  active: Generated<boolean>;
  carrierId: string;
  code: string;
  direction: string;
  id: Generated<string>;
  label: string;
  leadTimeDays: number;
  maxDimensionSumMm: number | null;
  maxHeightMm: number | null;
  maxInsuredValueCents: Int8 | null;
  maxLengthMm: number | null;
  maxWeightGrams: number | null;
  maxWidthMm: number | null;
  name: string;
}

export interface LogisticsCustomField {
  active: Generated<boolean>;
  fieldType: string;
  id: Generated<string>;
  label: string;
  listValues: Generated<Json>;
  principalId: string;
  rank: Generated<number>;
  required: Generated<boolean>;
}

export interface LogisticsDailyStockSnapshot {
  failure: string | null;
  id: Generated<string>;
  siteId: string;
  snapshotDate: string;
  state: string;
  takenAt: Generated<Timestamp>;
}

export interface LogisticsDailyStockSnapshotLine {
  handlingUnits: number;
  itemId: string;
  locationId: string;
  principalId: string;
  qualityStateId: string;
  quantity: number;
  snapshotId: string;
  volumeCm3: Int8 | null;
}

export interface LogisticsDock {
  active: Generated<boolean>;
  code: string;
  id: Generated<string>;
  zoneId: string;
}

export interface LogisticsExpectedReceipt {
  expectedArrivalDate: string;
  id: Generated<string>;
  number: string;
  principalId: string;
  siteId: string;
  state: Generated<string>;
  supplierId: string;
  version: Generated<number>;
}

export interface LogisticsExpectedReceiptLine {
  expectedQuantity: number;
  expectedReceiptId: string;
  id: Generated<string>;
  itemId: string;
  lineNumber: number;
  servedQuantity: Generated<number>;
}

export interface LogisticsFixedPickLocation {
  itemId: string;
  locationId: string;
  replenishmentTarget: number;
  replenishmentThreshold: number;
}

export interface LogisticsHandlingUnit {
  active: Generated<boolean>;
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  locationId: string | null;
  ownerPartyId: string | null;
  parentId: string | null;
  siteId: string;
  typeId: string;
  version: Generated<number>;
}

export interface LogisticsHandlingUnitType {
  active: Generated<boolean>;
  code: string;
  heightMm: number | null;
  id: Generated<string>;
  label: string;
  lengthMm: number | null;
  returnable: Generated<boolean>;
  tareWeightGrams: number | null;
  widthMm: number | null;
}

export interface LogisticsInboundArrival {
  arrivedAt: Generated<Timestamp>;
  carrierId: string | null;
  dockId: string;
  id: Generated<string>;
  releasedAt: Timestamp | null;
  siteId: string;
  vehicleIdentification: string;
  version: Generated<number>;
}

export interface LogisticsItem {
  adrClass: string | null;
  adrPackingGroup: string | null;
  adrUnNumber: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  declaredValueCents: Int8 | null;
  familyId: string | null;
  id: Generated<string>;
  isKit: Generated<boolean>;
  longLabel: string | null;
  pickingRule: string | null;
  principalId: string;
  serialBatchTracking: Generated<boolean>;
  shortLabel: string;
  state: Generated<string>;
  trackingMode: string;
  tracksExpiryDate: Generated<boolean>;
  tracksManufacturingDate: Generated<boolean>;
  version: Generated<number>;
}

export interface LogisticsItemBarcode {
  active: Generated<boolean>;
  code: string;
  itemId: string;
  nature: string;
  packagingRank: number | null;
  principalId: string;
}

export interface LogisticsItemCustomValue {
  customFieldId: string;
  itemId: string;
  value: Json;
}

export interface LogisticsItemDeclaredValue {
  currency: string | null;
  id: Generated<string>;
  itemId: string;
  setAt: Generated<Timestamp>;
  valueCents: Int8 | null;
}

export interface LogisticsItemFamily {
  active: Generated<boolean>;
  code: string;
  id: Generated<string>;
  name: string;
  parentId: string | null;
  principalId: string;
}

export interface LogisticsItemSubstitution {
  replacedItemId: string;
  replacingItemId: string;
}

export interface LogisticsKitComponent {
  componentItemId: string;
  kitItemId: string;
  quantity: number;
}

export interface LogisticsLocation {
  acceptedQualityCodes: Generated<string[]>;
  active: Generated<boolean>;
  address: string;
  barcode: string;
  dockId: string | null;
  id: Generated<string>;
  maxVolumeCm3: number | null;
  maxWeightGrams: number | null;
  overflow: Generated<boolean>;
  partyId: string | null;
  segments: Json;
  siteId: string;
  supportCapacity: number | null;
  traversalRank: number;
  type: string;
  virtualFamily: string | null;
  zoneId: string;
}

export interface LogisticsMovementReason {
  active: Generated<boolean>;
  commentRequired: Generated<boolean>;
  id: Generated<string>;
  label: string;
  nature: string;
}

export interface LogisticsPackagingLevel {
  grossWeightGrams: number | null;
  heightMm: number | null;
  itemId: string;
  lengthMm: number | null;
  name: string;
  rank: number;
  unitsOfLowerLevel: number | null;
  widthMm: number | null;
}

export interface LogisticsParty {
  active: Generated<boolean>;
  anonymizedAt: Timestamp | null;
  code: string;
  createdAt: Generated<Timestamp>;
  email: string | null;
  family: string;
  id: Generated<string>;
  issuesDestructionCertificate: Generated<boolean>;
  lastFlowAt: Timestamp | null;
  mergedIntoPartyId: string | null;
  name: string;
  phone: string | null;
  principalId: string | null;
  subcontractingNature: string | null;
  toComplete: Generated<boolean>;
}

export interface LogisticsPartyAddress {
  active: Generated<boolean>;
  city: string | null;
  countryCode: string;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  line1: string | null;
  line2: string | null;
  partyId: string;
  postalCode: string | null;
  recipient: string | null;
  usage: string;
}

export interface LogisticsPrincipal {
  active: Generated<boolean>;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  code: string;
  countryCode: string | null;
  currency: string | null;
  email: string | null;
  endCustomerRetentionMonths: number | null;
  id: Generated<string>;
  internal: Generated<boolean>;
  name: string;
  phone: string | null;
  pickingRule: Generated<string>;
  postalCode: string | null;
  principalGroup: string | null;
}

export interface LogisticsQualityState {
  active: Generated<boolean>;
  code: string;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  label: string;
  pickable: Generated<boolean>;
  principalId: string;
  rank: Generated<number>;
  suggestedLocationType: string | null;
}

export interface LogisticsRepairBomComponent {
  componentItemId: string;
  itemId: string;
  quantity: number;
}

export interface LogisticsSerializedUnit {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  itemId: string;
  principalId: string;
  serialNumber: string;
  warrantyEndDate: string | null;
}

export interface LogisticsStockHold {
  allowsMove: Generated<boolean>;
  batchId: string | null;
  id: Generated<string>;
  itemId: string | null;
  liftedAt: Timestamp | null;
  liftedBy: string | null;
  liftReason: string | null;
  locationId: string | null;
  origin: Generated<string>;
  placedAt: Generated<Timestamp>;
  placedBy: string | null;
  plannedLiftOn: string | null;
  reason: string;
  scope: string;
  serializedUnitId: string | null;
  stockUnitId: string | null;
}

export interface LogisticsStockMove {
  completedAt: Timestamp | null;
  fromLocationId: string;
  handlingUnitId: string | null;
  id: Generated<string>;
  siteId: string;
  startedAt: Generated<Timestamp>;
  startedBy: string;
}

export interface LogisticsStockMovement {
  authorUserId: string | null;
  comment: string | null;
  correctsMovementId: string | null;
  direction: Generated<number>;
  flowId: string | null;
  flowType: string | null;
  fromHandlingUnitId: string | null;
  fromLocationId: string | null;
  fromQualityStateId: string | null;
  groupId: string | null;
  id: Generated<string>;
  itemId: string;
  nature: string;
  occurredAt: Generated<Timestamp>;
  principalId: string;
  quantity: number;
  reasonId: string | null;
  serializedUnitId: string | null;
  siteId: string;
  stockUnitId: string;
  toHandlingUnitId: string | null;
  toLocationId: string | null;
  toQualityStateId: string | null;
  workstationId: string | null;
}

export interface LogisticsStockReservation {
  demandId: string;
  demandType: string;
  reservedAt: Generated<Timestamp>;
  stockUnitId: string;
}

export interface LogisticsStockUnit {
  batchId: string | null;
  enteredAt: Generated<Timestamp>;
  entryValueCents: Int8 | null;
  expiryDate: string | null;
  handlingUnitId: string | null;
  id: Generated<string>;
  itemId: string;
  locationId: string;
  manufacturingDate: string | null;
  moveId: string | null;
  originFlowId: string | null;
  originFlowType: string | null;
  principalId: string;
  qualityStateId: string;
  quantity: number;
  serializedUnitId: string | null;
  siteId: string;
  version: Generated<number>;
}

export interface LogisticsUserPrincipalRestriction {
  principalId: string;
  userId: string;
}

export interface LogisticsZone {
  active: Generated<boolean>;
  addressPattern: Json | null;
  addressSeparator: Generated<string>;
  code: string;
  cohabitation: string;
  id: Generated<string>;
  name: string;
  pickMode: Generated<string>;
  principalId: string | null;
  purpose: string;
  putawayMode: Generated<string>;
  siteId: string;
  traversal: Generated<string>;
  visitRank: Generated<number>;
}

export interface DB {
  "foundation.gesture": FoundationGesture;
  "foundation.numberingCounter": FoundationNumberingCounter;
  "foundation.numberingScheme": FoundationNumberingScheme;
  "foundation.provider": FoundationProvider;
  "foundation.role": FoundationRole;
  "foundation.rolePermission": FoundationRolePermission;
  "foundation.session": FoundationSession;
  "foundation.site": FoundationSite;
  "foundation.siteClosure": FoundationSiteClosure;
  "foundation.siteOpeningRange": FoundationSiteOpeningRange;
  "foundation.team": FoundationTeam;
  "foundation.teamMember": FoundationTeamMember;
  "foundation.traceEvent": FoundationTraceEvent;
  "foundation.traceEventObject": FoundationTraceEventObject;
  "foundation.user": FoundationUser;
  "foundation.userRole": FoundationUserRole;
  "foundation.userSite": FoundationUserSite;
  "foundation.workstation": FoundationWorkstation;
  "logistics.batch": LogisticsBatch;
  "logistics.carrierAccount": LogisticsCarrierAccount;
  "logistics.carrierService": LogisticsCarrierService;
  "logistics.customField": LogisticsCustomField;
  "logistics.dailyStockSnapshot": LogisticsDailyStockSnapshot;
  "logistics.dailyStockSnapshotLine": LogisticsDailyStockSnapshotLine;
  "logistics.dock": LogisticsDock;
  "logistics.expectedReceipt": LogisticsExpectedReceipt;
  "logistics.expectedReceiptLine": LogisticsExpectedReceiptLine;
  "logistics.fixedPickLocation": LogisticsFixedPickLocation;
  "logistics.handlingUnit": LogisticsHandlingUnit;
  "logistics.handlingUnitType": LogisticsHandlingUnitType;
  "logistics.inboundArrival": LogisticsInboundArrival;
  "logistics.item": LogisticsItem;
  "logistics.itemBarcode": LogisticsItemBarcode;
  "logistics.itemCustomValue": LogisticsItemCustomValue;
  "logistics.itemDeclaredValue": LogisticsItemDeclaredValue;
  "logistics.itemFamily": LogisticsItemFamily;
  "logistics.itemSubstitution": LogisticsItemSubstitution;
  "logistics.kitComponent": LogisticsKitComponent;
  "logistics.location": LogisticsLocation;
  "logistics.movementReason": LogisticsMovementReason;
  "logistics.packagingLevel": LogisticsPackagingLevel;
  "logistics.party": LogisticsParty;
  "logistics.partyAddress": LogisticsPartyAddress;
  "logistics.principal": LogisticsPrincipal;
  "logistics.qualityState": LogisticsQualityState;
  "logistics.repairBomComponent": LogisticsRepairBomComponent;
  "logistics.serializedUnit": LogisticsSerializedUnit;
  "logistics.stockHold": LogisticsStockHold;
  "logistics.stockMove": LogisticsStockMove;
  "logistics.stockMovement": LogisticsStockMovement;
  "logistics.stockReservation": LogisticsStockReservation;
  "logistics.stockUnit": LogisticsStockUnit;
  "logistics.userPrincipalRestriction": LogisticsUserPrincipalRestriction;
  "logistics.zone": LogisticsZone;
}
