/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface FoundationGesture {
  authorUserId: string | null;
  id: string;
  name: string;
  outcome: string;
  receivedAt: Generated<Timestamp>;
  response: Json;
  workstationId: string | null;
}

export interface FoundationNumberingCounter {
  nextValue: Int8;
  objectType: string;
  partitionKey: string;
}

export interface FoundationNumberingScheme {
  objectType: string;
  segments: Json;
}

export interface FoundationProvider {
  name: string | null;
  singleton: Generated<boolean>;
}

export interface FoundationRole {
  id: Generated<string>;
  name: string;
  nature: string;
  template: string | null;
}

export interface FoundationRolePermission {
  permission: string;
  roleId: string;
}

export interface FoundationSession {
  expiresAt: Timestamp;
  id: Generated<string>;
  revoked: Generated<boolean>;
  tokenHash: Buffer;
  userId: string;
}

export interface FoundationSite {
  active: Generated<boolean>;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  code: string;
  countryCode: Generated<string>;
  id: Generated<string>;
  name: string;
  postalCode: string | null;
  timeZone: string;
}

export interface FoundationSiteClosure {
  day: string;
  kind: string;
  label: string;
  siteId: string;
}

export interface FoundationSiteOpeningRange {
  closesAt: string;
  opensAt: string;
  siteId: string;
  weekday: number;
}

export interface FoundationTeam {
  active: Generated<boolean>;
  id: Generated<string>;
  leadUserId: string | null;
  name: string;
  siteId: string;
}

export interface FoundationTeamMember {
  teamId: string;
  userId: string;
}

export interface FoundationTraceEvent {
  authorUserId: string | null;
  data: Generated<Json>;
  decisionTrace: Json | null;
  gestureId: string | null;
  id: Generated<string>;
  occurredAt: Generated<Timestamp>;
  origin: string | null;
  originAt: Timestamp | null;
  teamId: string | null;
  type: string;
  workstationId: string | null;
}

export interface FoundationTraceEventObject {
  eventId: string;
  objectId: string;
  objectType: string;
  occurredAt: Timestamp;
}

export interface FoundationUser {
  active: Generated<boolean>;
  displayName: string;
  email: string | null;
  id: Generated<string>;
  loginName: string;
  passwordHash: string;
  reportsToUserId: string | null;
}

export interface FoundationUserRole {
  roleId: string;
  userId: string;
}

export interface FoundationUserSite {
  execution: Generated<boolean>;
  siteId: string;
  userId: string;
}

export interface FoundationWorkstation {
  id: Generated<string>;
  name: string;
  revoked: Generated<boolean>;
  siteId: string;
}

export interface LogisticsCarrierAccount {
  accountNumber: string;
  active: Generated<boolean>;
  carrierId: string;
  contractReference: string | null;
  id: Generated<string>;
  principalId: string | null;
}

export interface LogisticsCarrierService {
  acceptsDangerousGoods: Generated<boolean>;
  active: Generated<boolean>;
  carrierId: string;
  code: string;
  direction: string;
  id: Generated<string>;
  label: string;
  leadTimeDays: number;
  maxDimensionSumMm: number | null;
  maxHeightMm: number | null;
  maxInsuredValueCents: Int8 | null;
  maxLengthMm: number | null;
  maxWeightGrams: number | null;
  maxWidthMm: number | null;
  name: string;
}

export interface LogisticsCustomField {
  active: Generated<boolean>;
  fieldType: string;
  id: Generated<string>;
  label: string;
  listValues: Generated<Json>;
  principalId: string;
  rank: Generated<number>;
  required: Generated<boolean>;
}

export interface LogisticsDock {
  active: Generated<boolean>;
  code: string;
  id: Generated<string>;
  zoneId: string;
}

export interface LogisticsExpectedReceipt {
  expectedArrivalDate: string;
  id: Generated<string>;
  number: string;
  principalId: string;
  siteId: string;
  state: Generated<string>;
  supplierId: string;
  version: Generated<number>;
}

export interface LogisticsExpectedReceiptLine {
  expectedQuantity: number;
  expectedReceiptId: string;
  id: Generated<string>;
  itemId: string;
  lineNumber: number;
  servedQuantity: Generated<number>;
}

export interface LogisticsInboundArrival {
  arrivedAt: Generated<Timestamp>;
  carrierId: string | null;
  dockId: string;
  id: Generated<string>;
  releasedAt: Timestamp | null;
  siteId: string;
  vehicleIdentification: string;
  version: Generated<number>;
}

export interface LogisticsItem {
  adrClass: string | null;
  adrPackingGroup: string | null;
  adrUnNumber: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  declaredValueCents: Int8 | null;
  familyId: string | null;
  id: Generated<string>;
  isKit: Generated<boolean>;
  longLabel: string | null;
  principalId: string;
  serialBatchTracking: Generated<boolean>;
  shortLabel: string;
  state: Generated<string>;
  trackingMode: string;
  tracksExpiryDate: Generated<boolean>;
  tracksManufacturingDate: Generated<boolean>;
  version: Generated<number>;
}

export interface LogisticsItemBarcode {
  active: Generated<boolean>;
  code: string;
  itemId: string;
  nature: string;
  packagingRank: number | null;
  principalId: string;
}

export interface LogisticsItemCustomValue {
  customFieldId: string;
  itemId: string;
  value: Json;
}

export interface LogisticsItemDeclaredValue {
  currency: string | null;
  id: Generated<string>;
  itemId: string;
  setAt: Generated<Timestamp>;
  valueCents: Int8 | null;
}

export interface LogisticsItemFamily {
  active: Generated<boolean>;
  code: string;
  id: Generated<string>;
  name: string;
  parentId: string | null;
  principalId: string;
}

export interface LogisticsItemSubstitution {
  replacedItemId: string;
  replacingItemId: string;
}

export interface LogisticsKitComponent {
  componentItemId: string;
  kitItemId: string;
  quantity: number;
}

export interface LogisticsLocation {
  active: Generated<boolean>;
  address: string;
  dockId: string | null;
  id: Generated<string>;
  overflow: Generated<boolean>;
  routeSequence: number;
  segments: Json;
  siteId: string;
  supportCapacity: number | null;
  type: string;
  zoneId: string;
}

export interface LogisticsPackagingLevel {
  grossWeightGrams: number | null;
  heightMm: number | null;
  itemId: string;
  lengthMm: number | null;
  name: string;
  rank: number;
  unitsOfLowerLevel: number | null;
  widthMm: number | null;
}

export interface LogisticsParty {
  active: Generated<boolean>;
  anonymizedAt: Timestamp | null;
  code: string;
  createdAt: Generated<Timestamp>;
  email: string | null;
  family: string;
  id: Generated<string>;
  issuesDestructionCertificate: Generated<boolean>;
  lastFlowAt: Timestamp | null;
  mergedIntoPartyId: string | null;
  name: string;
  phone: string | null;
  principalId: string | null;
  subcontractingNature: string | null;
  toComplete: Generated<boolean>;
}

export interface LogisticsPartyAddress {
  active: Generated<boolean>;
  city: string | null;
  countryCode: string;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  line1: string | null;
  line2: string | null;
  partyId: string;
  postalCode: string | null;
  recipient: string | null;
  usage: string;
}

export interface LogisticsPrincipal {
  active: Generated<boolean>;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  code: string;
  countryCode: string | null;
  currency: string | null;
  email: string | null;
  endCustomerRetentionMonths: number | null;
  id: Generated<string>;
  internal: Generated<boolean>;
  name: string;
  phone: string | null;
  postalCode: string | null;
  principalGroup: string | null;
}

export interface LogisticsRepairBomComponent {
  componentItemId: string;
  itemId: string;
  quantity: number;
}

export interface LogisticsUserPrincipalRestriction {
  principalId: string;
  userId: string;
}

export interface LogisticsZone {
  active: Generated<boolean>;
  addressPattern: Json | null;
  addressSeparator: Generated<string>;
  code: string;
  cohabitation: string;
  id: Generated<string>;
  name: string;
  principalId: string | null;
  purpose: string;
  putawayMode: Generated<string>;
  siteId: string;
}

export interface DB {
  "foundation.gesture": FoundationGesture;
  "foundation.numberingCounter": FoundationNumberingCounter;
  "foundation.numberingScheme": FoundationNumberingScheme;
  "foundation.provider": FoundationProvider;
  "foundation.role": FoundationRole;
  "foundation.rolePermission": FoundationRolePermission;
  "foundation.session": FoundationSession;
  "foundation.site": FoundationSite;
  "foundation.siteClosure": FoundationSiteClosure;
  "foundation.siteOpeningRange": FoundationSiteOpeningRange;
  "foundation.team": FoundationTeam;
  "foundation.teamMember": FoundationTeamMember;
  "foundation.traceEvent": FoundationTraceEvent;
  "foundation.traceEventObject": FoundationTraceEventObject;
  "foundation.user": FoundationUser;
  "foundation.userRole": FoundationUserRole;
  "foundation.userSite": FoundationUserSite;
  "foundation.workstation": FoundationWorkstation;
  "logistics.carrierAccount": LogisticsCarrierAccount;
  "logistics.carrierService": LogisticsCarrierService;
  "logistics.customField": LogisticsCustomField;
  "logistics.dock": LogisticsDock;
  "logistics.expectedReceipt": LogisticsExpectedReceipt;
  "logistics.expectedReceiptLine": LogisticsExpectedReceiptLine;
  "logistics.inboundArrival": LogisticsInboundArrival;
  "logistics.item": LogisticsItem;
  "logistics.itemBarcode": LogisticsItemBarcode;
  "logistics.itemCustomValue": LogisticsItemCustomValue;
  "logistics.itemDeclaredValue": LogisticsItemDeclaredValue;
  "logistics.itemFamily": LogisticsItemFamily;
  "logistics.itemSubstitution": LogisticsItemSubstitution;
  "logistics.kitComponent": LogisticsKitComponent;
  "logistics.location": LogisticsLocation;
  "logistics.packagingLevel": LogisticsPackagingLevel;
  "logistics.party": LogisticsParty;
  "logistics.partyAddress": LogisticsPartyAddress;
  "logistics.principal": LogisticsPrincipal;
  "logistics.repairBomComponent": LogisticsRepairBomComponent;
  "logistics.userPrincipalRestriction": LogisticsUserPrincipalRestriction;
  "logistics.zone": LogisticsZone;
}
