import type { LabelCatalog } from './fr.js';

/** Libellés anglais, par utilisateur (RG-EXI-079). Mêmes clés que le français, imposées par le typage. */
export const en: LabelCatalog = {
  application: {
    name: 'Cairn WMS',
  },
  shell: {
    home: 'Home',
    dismiss: 'Dismiss',
  },
  navigation: {
    office: 'Office',
    receptions: 'Receptions',
  },
  expectedReceipt: {
    openList: 'Open expected receipts',
    create: 'Enter an expected receipt',
    newTitle: 'New expected receipt',
    title: 'Expected receipt {{number}}',
    number: 'Expected receipt',
    principal: 'Principal',
    supplier: 'Supplier',
    expectedArrivalDate: 'Expected arrival',
    lineCount: 'Lines',
    state: 'State',
    states: { open: 'Open', settled: 'Settled', cancelled: 'Cancelled' },
    lines: 'Expected receipt lines',
    item: 'Item',
    shortLabel: 'Label',
    quantity: 'Quantity',
    expectedQuantity: 'Expected',
    servedQuantity: 'Served',
    remainingQuantity: 'Remaining',
    addLine: 'Add a line',
    removeLine: 'Remove the line',
    save: 'Save the expected receipt',
    choose: 'Choose…',
    none: 'No open expected receipt on this site.',
  },
  dock: {
    list: 'Docks',
    title: 'Dock {{code}}',
    free: 'Free',
    occupied: 'Occupied',
    noVehicle: 'No vehicle',
    arrival: 'Arrival · {{vehicle}}',
    openedBy: 'Opened by {{name}} at {{time}}',
    occupiedSince: 'Occupied for',
  },
  arrival: {
    open: 'Open an arrival',
    title: 'New arrival at dock {{code}}',
    vehicle: 'Vehicle',
    carrier: 'Carrier',
    noCarrier: 'No carrier',
    submit: 'Open the arrival',
    cancel: 'Cancel',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    remove: 'Remove',
    edit: 'Edit',
    create: 'Create',
    activate: 'Activate',
    deactivate: 'Deactivate',
    active: 'Active',
    inactive: 'Inactive',
    none: 'None',
    saved: 'Saved.',
    yes: 'Yes',
    no: 'No',
  },
  administration: {
    group: 'Administration',
    settings: 'Settings',
    usersAndTeams: 'Users and teams',
    principals: 'Principals',
    sites: 'Sites',
    numbering: 'Numbering',
    provider: 'Provider',
    workstations: 'Workstations',
    users: 'Users',
    roles: 'Roles',
    teams: 'Teams',
    remaining: 'Still to settle: {{detail}}.',
  },
  site: {
    create: 'Create a site',
    newTitle: 'New site',
    title: 'Site {{code}}',
    code: 'Code',
    name: 'Label',
    city: 'City',
    zoneCount: 'Zones',
    state: 'State',
    timeZone: 'Time zone',
    addressLine1: 'Address',
    addressLine2: 'Address line 2',
    postalCode: 'Postal code',
    countryCode: 'Country',
    codeLocked: 'The code can no longer change: the site has already been used.',
    activation: 'Activation',
    missing: 'To activate the site, it still lacks: {{missing}}.',
    missingAddress: 'an address',
    missingZone: 'an active zone',
    ready: 'The site can be activated.',
    calendar: 'Calendar',
    calendarEmpty: 'Without opening ranges, the site counts as always open: its durations are not qualified.',
    opensAt: 'Opens',
    closesAt: 'Closes',
    addRange: 'Add a range',
    closed: 'Closed',
    closures: 'Public holidays and closures',
    day: 'Date',
    label: 'Reason',
    kind: 'Kind',
    kinds: { publicHoliday: 'Public holiday', exceptional: 'Exceptional closure' },
    addClosure: 'Add a closure',
    addPublicHolidays: 'Add the {{year}} public holidays',
    noClosure: 'No closed day.',
    zones: 'Zones',
    addZone: 'Add a zone',
    noZone: 'No zone: add one to be able to activate the site.',
    purpose: 'Purpose',
    cohabitation: 'Cohabitation',
    reservedFor: 'Reserved principal',
    list: 'Sites',
  },
  weekday: {
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
  },
  zonePurpose: {
    storage: 'Storage',
    picking: 'Picking',
    receiving: 'Receiving',
    shipping: 'Shipping',
    preparation: 'Preparation',
    consolidation: 'Consolidation',
    quarantine: 'Quarantine',
    dispute: 'Dispute',
    workshop: 'Workshop',
    destruction: 'Destruction',
    virtual: 'Virtual',
  },
  cohabitation: { single: 'Single principal', shared: 'Shared' },
  principalAdmin: {
    list: 'Principals',
    create: 'Create a principal',
    newTitle: 'New principal',
    code: 'Code',
    name: 'Label',
    group: 'Group',
    internal: 'Internal',
    email: 'Email',
    phone: 'Phone',
    state: 'State',
    address: 'Contact details',
  },
  role: {
    list: 'Roles',
    create: 'Compose a role',
    newTitle: 'New role',
    name: 'Label',
    nature: 'Nature',
    natures: { operational: 'Operational', administrative: 'Administrative' },
    natureHint:
      'An operational role passes its execution rights on to the supervisor; an administrative one only passes visibility.',
    template: 'Template',
    holders: 'Holders',
    permissions: 'Permissions',
    heldBy: 'This role is held by {{count}} user(s): the change applies to each of them.',
    delete: 'Delete the role',
  },
  permissionDomain: { reception: 'Reception', settings: 'Settings' },
  permission: {
    createExpectedReceipt: 'Enter an expected receipt',
    openInboundArrival: 'Open an arrival',
    administerProvider: 'Administer the provider',
    administerSites: 'Administer sites, calendars and zones',
    administerPrincipals: 'Administer principals',
    administerRoles: 'Compose roles',
    administerUsers: 'Administer users',
    administerExecutionSites: 'Set execution sites',
    administerTeams: 'Administer teams',
    administerNumbering: 'Compose numbering',
    declareWorkstation: 'Declare and revoke workstations',
  },
  user: {
    list: 'Users',
    create: 'Create a user',
    newTitle: 'New user',
    identity: 'Identity',
    displayName: 'Name',
    loginName: 'Login name',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least twelve characters. When editing, leave empty to keep the current one.',
    roles: 'Roles',
    sites: 'Sites',
    team: 'Team',
    reportsTo: 'Reports to',
    executionSites: 'Execution sites',
    executionHint: 'Among their sites, those where they act; elsewhere they only consult.',
    ownExecution: 'No one changes their own execution sites.',
    restrictions: 'Restrictions by principal',
    restrictionsHint: 'Exception: without restriction, the user sees every principal of their sites.',
    effectivePermissions: 'Effective permissions',
    state: 'State',
    noSiteWarning: 'Attached to no site, this user sees no operational data.',
  },
  team: {
    list: 'Teams',
    create: 'Create a team',
    newTitle: 'New team',
    name: 'Name',
    site: 'Site',
    lead: 'Team lead',
    noLead: 'No team lead',
    members: 'Members',
    state: 'State',
  },
  numbering: {
    list: 'Numbering schemes',
    objectType: 'Object type',
    composition: 'Composition',
    example: 'Example',
    segment: 'Segment',
    width: 'Digits',
    value: 'Text',
    addSegment: 'Add a segment',
    kinds: {
      literal: 'Fixed text',
      site: 'Site code',
      principal: 'Principal code',
      year: 'Year',
      month: 'Month',
      counter: 'Counter',
    },
    problems: {
      leadingLiteralRequired: 'The scheme starts with a fixed text naming the object type.',
      leadingLiteralTaken: 'This leading text already belongs to another object type, or prefixes it.',
      singleCounterRequired: 'The scheme holds one counter, and only one.',
      yearRequiredForMonth: 'The month comes with the year.',
      separatorRequired: 'Two variable-length codes are separated by a fixed text.',
    },
    objectTypes: { ExpectedReceipt: 'Expected receipt' },
  },
  provider: { title: 'Provider', name: 'Provider name', unnamed: 'The provider has no name yet.' },
  workstationAdmin: {
    list: 'Declared workstations',
    name: 'Workstation name',
    site: 'Site',
    state: 'State',
    revoked: 'Revoked',
    revoke: 'Revoke',
    declare: 'Declare this browser as a workstation',
    declareTitle: 'This browser',
    current: 'This browser is the workstation “{{name}}”.',
    undeclared: 'This browser is not a declared workstation: no gesture is possible here.',
  },
  siteSelector: { label: 'Site' },
  remainingKind: { expectedReceipts: 'open expected receipt(s)', inboundArrivals: 'open arrival(s)' },
  session: {
    title: 'Open a session',
    loginName: 'Login name',
    password: 'Password',
    open: 'Open the session',
    close: 'Close the session',
  },
  workstation: {
    label: 'Workstation',
    undeclared: 'Undeclared workstation',
  },
  failure: {
    noResponse:
      'The server is not responding. Check the connection, then try again: nothing will be recorded twice.',
  },
  refusal: {
    unknownWorkstation: 'This workstation does not exist.',
    codeTaken: 'This code is already in use.',
    codeLocked: 'The code can no longer change: the site has already been used.',
    unknownTimeZone: 'This time zone does not exist.',
    activationIncomplete: 'The site cannot be activated yet: it lacks an address or a zone.',
    activityRemaining: 'Stock or open flows remain to be settled.',
    overlappingRanges: 'Two opening ranges of the same day overlap, or a range closes before it opens.',
    unknownZone: 'This zone does not exist.',
    principalRequired: 'A single-principal zone names its reserved principal.',
    foreignStock: 'The zone holds stock of another principal: it cannot be reserved.',
    internalPrincipal: 'The internal principal cannot be deactivated.',
    unknownRole: 'This role does not exist.',
    nameTaken: 'This name is already in use.',
    lastRoleAdministrator: 'At least one active user must keep role administration.',
    roleHeld: 'This role is still held by users.',
    unknownUser: 'This user does not exist.',
    loginNameTaken: 'This login name is already in use.',
    passwordRequired: 'A new user receives a password.',
    unknownTeam: 'This team does not exist or is no longer active.',
    teamOutsideSites: 'The team belongs to a site the user is not attached to.',
    hierarchyCycle: 'This reporting line would place the user under someone they supervise.',
    siteRequired: 'A user is activated with at least one site.',
    ownExecutionSites: 'No one changes their own execution sites.',
    executionOutsideSites: 'An execution site is chosen among the attached sites.',
    leadOutsideSite: 'The team lead is not attached to the team’s site.',
    teamHasMembers: 'The team still has members: move them before deactivating it.',
    unknownObjectType: 'This object type has no numbering scheme.',
    numberingNotUnique: 'This composition does not guarantee unique identifiers.',
    unknownDock: 'This dock does not exist or is no longer active.',
    dockOccupied: 'Dock {{dock}} is already occupied by a vehicle.',
    unknownCarrier: 'This carrier does not exist or is no longer active.',
    unknownPrincipal: 'This principal does not exist or is no longer active.',
    unknownSupplier: 'This supplier does not belong to the principal, or is no longer active.',
    unknownItem: 'An item does not belong to the principal, or can no longer be received.',
    duplicateItem: 'An item appears on two lines.',
    invalidInput: 'The input is incomplete or invalid.',
    notAuthenticated: 'You must sign in.',
    permissionDenied: 'You do not have permission for this gesture.',
    outOfScope: 'This object is outside your scope.',
    undeclaredWorkstation: 'This workstation is not declared: no gesture is possible.',
    editLockHeldByOther: '{{holder}} holds the edit lock.',
    invalidCredentials: 'Incorrect login name or password.',
    tooManyAttempts: 'Too many attempts: try again in a few minutes.',
    workstationNameTaken: 'A workstation is already named {{name}}.',
    unknownSite: 'This site does not exist.',
  },
};
