import type { LabelCatalog } from './fr.js';

/** Libellés anglais, par utilisateur (RG-EXI-079). Mêmes clés que le français, imposées par le typage. */
export const en: LabelCatalog = {
  application: {
    name: 'Cairn WMS',
  },
  shell: {
    home: 'Home',
    dismiss: 'Dismiss',
  },
  navigation: {
    office: 'Office',
    receptions: 'Receptions',
    items: 'Items',
  },
  expectedReceipt: {
    openList: 'Open expected receipts',
    create: 'Enter an expected receipt',
    newTitle: 'New expected receipt',
    title: 'Expected receipt {{number}}',
    number: 'Expected receipt',
    principal: 'Principal',
    supplier: 'Supplier',
    expectedArrivalDate: 'Expected arrival',
    lineCount: 'Lines',
    state: 'State',
    states: { open: 'Open', settled: 'Settled', cancelled: 'Cancelled' },
    lines: 'Expected receipt lines',
    item: 'Item',
    shortLabel: 'Label',
    quantity: 'Quantity',
    expectedQuantity: 'Expected',
    servedQuantity: 'Served',
    remainingQuantity: 'Remaining',
    addLine: 'Add a line',
    removeLine: 'Remove the line',
    save: 'Save the expected receipt',
    choose: 'Choose…',
    none: 'No open expected receipt on this site.',
  },
  dock: {
    list: 'Docks',
    title: 'Dock {{code}}',
    free: 'Free',
    occupied: 'Occupied',
    noVehicle: 'No vehicle',
    arrival: 'Arrival · {{vehicle}}',
    openedBy: 'Opened by {{name}} at {{time}}',
    occupiedSince: 'Occupied for',
  },
  arrival: {
    open: 'Open an arrival',
    title: 'New arrival at dock {{code}}',
    vehicle: 'Vehicle',
    carrier: 'Carrier',
    noCarrier: 'No carrier',
    submit: 'Open the arrival',
    cancel: 'Cancel',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    remove: 'Remove',
    edit: 'Edit',
    create: 'Create',
    activate: 'Activate',
    deactivate: 'Deactivate',
    active: 'Active',
    inactive: 'Inactive',
    none: 'None',
    saved: 'Saved.',
    yes: 'Yes',
    no: 'No',
  },
  administration: {
    group: 'Administration',
    settings: 'Settings',
    usersAndTeams: 'Users and teams',
    principals: 'Principals',
    sites: 'Sites',
    numbering: 'Numbering',
    provider: 'Provider',
    workstations: 'Workstations',
    users: 'Users',
    roles: 'Roles',
    teams: 'Teams',
    remaining: 'Still to settle: {{detail}}.',
  },
  site: {
    create: 'Create a site',
    newTitle: 'New site',
    title: 'Site {{code}}',
    code: 'Code',
    name: 'Label',
    city: 'City',
    zoneCount: 'Zones',
    state: 'State',
    timeZone: 'Time zone',
    addressLine1: 'Address',
    addressLine2: 'Address line 2',
    postalCode: 'Postal code',
    countryCode: 'Country',
    codeLocked: 'The code can no longer change: the site has already been used.',
    activation: 'Activation',
    missing: 'To activate the site, it still lacks: {{missing}}.',
    missingAddress: 'an address',
    missingZone: 'an active zone',
    ready: 'The site can be activated.',
    calendar: 'Calendar',
    calendarEmpty: 'Without opening ranges, the site counts as always open: its durations are not qualified.',
    opensAt: 'Opens',
    closesAt: 'Closes',
    addRange: 'Add a range',
    closed: 'Closed',
    closures: 'Public holidays and closures',
    day: 'Date',
    label: 'Reason',
    kind: 'Kind',
    kinds: { publicHoliday: 'Public holiday', exceptional: 'Exceptional closure' },
    addClosure: 'Add a closure',
    addPublicHolidays: 'Add the {{year}} public holidays',
    noClosure: 'No closed day.',
    zones: 'Zones',
    addZone: 'Add a zone',
    noZone: 'No zone: add one to be able to activate the site.',
    purpose: 'Purpose',
    cohabitation: 'Cohabitation',
    reservedFor: 'Reserved principal',
    list: 'Sites',
  },
  weekday: {
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
  },
  zonePurpose: {
    storage: 'Storage',
    picking: 'Picking',
    receiving: 'Receiving',
    shipping: 'Shipping',
    preparation: 'Preparation',
    consolidation: 'Consolidation',
    quarantine: 'Quarantine',
    dispute: 'Dispute',
    workshop: 'Workshop',
    destruction: 'Destruction',
    virtual: 'Virtual',
  },
  cohabitation: { single: 'Single principal', shared: 'Shared' },
  principalAdmin: {
    list: 'Principals',
    create: 'Create a principal',
    newTitle: 'New principal',
    code: 'Code',
    name: 'Label',
    group: 'Group',
    internal: 'Internal',
    email: 'Email',
    phone: 'Phone',
    state: 'State',
    address: 'Contact details',
    currency: 'Currency (ISO 4217)',
    currencyTitle: 'Currency',
    currencyHint: 'The principal’s single currency, in which the declared values of its items are expressed.',
  },
  role: {
    list: 'Roles',
    create: 'Compose a role',
    newTitle: 'New role',
    name: 'Label',
    nature: 'Nature',
    natures: { operational: 'Operational', administrative: 'Administrative' },
    natureHint:
      'An operational role passes its execution rights on to the supervisor; an administrative one only passes visibility.',
    template: 'Template',
    holders: 'Holders',
    permissions: 'Permissions',
    heldBy: 'This role is held by {{count}} user(s): the change applies to each of them.',
    delete: 'Delete the role',
  },
  permissionDomain: {
    catalog: 'Item catalogue',
    partners: 'Parties',
    reception: 'Reception',
    settings: 'Settings',
  },
  permission: {
    managePrincipalParties: 'Manage suppliers and end customers',
    mergeEndCustomers: 'Merge two end customer records',
    anonymizeEndCustomers: 'Anonymise an end customer',
    administerProviderParties: 'Administer carriers and subcontractors',
    createExpectedReceipt: 'Enter an expected receipt',
    openInboundArrival: 'Open an arrival',
    administerProvider: 'Administer the provider',
    administerSites: 'Administer sites, calendars and zones',
    administerPrincipals: 'Administer principals',
    administerRoles: 'Compose roles',
    administerUsers: 'Administer users',
    administerExecutionSites: 'Set execution sites',
    administerTeams: 'Administer teams',
    administerNumbering: 'Compose numbering',
    declareWorkstation: 'Declare and revoke workstations',
    manageItems: 'Manage items and their families',
    manageCustomFields: 'Declare custom fields',
    createDraftItem: 'Create an item on the fly',
  },
  user: {
    list: 'Users',
    create: 'Create a user',
    newTitle: 'New user',
    identity: 'Identity',
    displayName: 'Name',
    loginName: 'Login name',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least twelve characters. When editing, leave empty to keep the current one.',
    roles: 'Roles',
    sites: 'Sites',
    team: 'Team',
    reportsTo: 'Reports to',
    executionSites: 'Execution sites',
    executionHint: 'Among their sites, those where they act; elsewhere they only consult.',
    ownExecution: 'No one changes their own execution sites.',
    restrictions: 'Restrictions by principal',
    restrictionsHint: 'Exception: without restriction, the user sees every principal of their sites.',
    effectivePermissions: 'Effective permissions',
    state: 'State',
    noSiteWarning: 'Attached to no site, this user sees no operational data.',
  },
  team: {
    list: 'Teams',
    create: 'Create a team',
    newTitle: 'New team',
    name: 'Name',
    site: 'Site',
    lead: 'Team lead',
    noLead: 'No team lead',
    members: 'Members',
    state: 'State',
  },
  numbering: {
    list: 'Numbering schemes',
    objectType: 'Object type',
    composition: 'Composition',
    example: 'Example',
    segment: 'Segment',
    width: 'Digits',
    value: 'Text',
    addSegment: 'Add a segment',
    kinds: {
      literal: 'Fixed text',
      site: 'Site code',
      principal: 'Principal code',
      year: 'Year',
      month: 'Month',
      counter: 'Counter',
    },
    problems: {
      leadingLiteralRequired: 'The scheme starts with a fixed text naming the object type.',
      leadingLiteralTaken: 'This leading text already belongs to another object type, or prefixes it.',
      singleCounterRequired: 'The scheme holds one counter, and only one.',
      yearRequiredForMonth: 'The month comes with the year.',
      separatorRequired: 'Two variable-length codes are separated by a fixed text.',
    },
    objectTypes: { ExpectedReceipt: 'Expected receipt' },
  },
  provider: { title: 'Provider', name: 'Provider name', unnamed: 'The provider has no name yet.' },
  workstationAdmin: {
    list: 'Declared workstations',
    name: 'Workstation name',
    site: 'Site',
    state: 'State',
    revoked: 'Revoked',
    revoke: 'Revoke',
    declare: 'Declare this browser as a workstation',
    declareTitle: 'This browser',
    current: 'This browser is the workstation “{{name}}”.',
    undeclared: 'This browser is not a declared workstation: no gesture is possible here.',
  },
  siteSelector: { label: 'Site' },
  remainingKind: { expectedReceipts: 'open expected receipt(s)', inboundArrivals: 'open arrival(s)' },
  party: {
    menu: 'Parties',
    principal: 'Principal',
    suppliers: 'Suppliers',
    endCustomers: 'End customers',
    carriers: 'Carriers',
    subcontractors: 'Subcontractors',
    duplicates: 'Potential duplicates',
    schedule: 'Anonymisation schedule',
    search: 'Search',
    create: 'Create',
    code: 'Code',
    codeHint: 'Leave empty for a generated key.',
    name: 'Company or person name',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    state: 'State',
    toComplete: 'To complete',
    anonymized: 'Anonymised end customer',
    merged: 'Merged record',
    readOnly: 'Read only: this record was merged or anonymised.',
    none: 'No party.',
    nature: 'Service nature',
    natures: {
      repair: 'Repair',
      destruction: 'Destruction',
      recycling: 'Recycling',
      refurbishment: 'Refurbishment',
      other: 'Other',
    },
    certificate: 'Issues a destruction certificate',
    identity: 'Identity',
    families: {
      supplier: 'Supplier',
      endCustomer: 'End customer',
      carrier: 'Carrier',
      subcontractor: 'Subcontractor',
    },
  },
  address: {
    title: 'Addresses',
    add: 'Add an address',
    usage: 'Usage',
    usages: { delivery: 'Delivery', return: 'Return', billing: 'Billing', headOffice: 'Head office' },
    isDefault: 'Default',
    recipient: 'Recipient',
    line1: 'Address',
    line2: 'Line 2',
    postalCode: 'Postal code',
    city: 'City',
    countryCode: 'Country',
    none: 'No address.',
    postalFormat: 'Expected format for this country: {{example}}.',
  },
  endCustomer: {
    lastFlow: 'Last flow',
    noFlow: 'No flow',
    dueOn: 'Anonymisation due',
    noRetention: 'No retention period declared: no automatic anonymisation.',
    history: 'History',
    historyEmpty: 'No order, shipment, return, case or dispute.',
    counters: 'Orders · returns · cases · disputes',
    anonymize: 'Anonymise',
    anonymizeTitle: 'Anonymise this end customer',
    anonymizeWarning:
      'Anonymisation is irreversible: name, addresses, phone and email will be erased. Flows stay readable.',
    reason: 'Reason',
    confirm: 'Anonymise for good',
    merge: 'Merge with another record',
    mergeTitle: 'Merge two records',
    other: 'Other record',
    kept: 'Kept record',
    absorbed: 'Merged record',
    takeFrom: 'Value kept',
    mergeWarning: 'The merge is final: the merged record stays readable, read only.',
    confirmMerge: 'Merge for good',
    reasons: { name: 'Same name', email: 'Same email', phone: 'Same phone' },
    compare: 'Compare',
  },
  schedule: {
    retention: 'Retention (months)',
    dueSoon: 'Due within 30 days',
    postponed: 'Postponed (open flows)',
    anonymized: 'Anonymised over 30 days',
    missing: 'Not declared',
  },
  carrier: {
    services: 'Services',
    addService: 'Add a service',
    serviceCode: 'Code',
    serviceName: 'Label',
    direction: 'Direction',
    directions: { outbound: 'Outbound', return: 'Return', both: 'Both ways' },
    maxWeightGrams: 'Max weight (g)',
    maxLengthMm: 'Max length (mm)',
    maxWidthMm: 'Max width (mm)',
    maxHeightMm: 'Max height (mm)',
    maxDimensionSumMm: 'Max sum of dimensions (mm)',
    maxInsuredValueCents: 'Max insured value (cents)',
    dangerousGoods: 'Accepts dangerous goods',
    label: 'Label',
    labels: { none: 'None', carrier: 'Generated by the carrier', provider: 'Generated by the provider' },
    leadTimeDays: 'Announced lead time (working days)',
    accounts: 'Accounts',
    addAccount: 'Add an account',
    accountNumber: 'Account number',
    contractReference: 'Contract reference',
    accountPrincipal: 'Principal',
    providerAccount: 'Provider account',
  },
  retention: {
    title: 'End customer data retention',
    months: 'Period (months)',
    hint: 'From the last flow. Empty: no automatic anonymisation.',
  },
  item: {
    menu: 'Items',
    list: 'Items',
    toComplete: 'Items to complete',
    toCompleteHint: 'Drafts, oldest first, with the stock they tie up.',
    principal: 'Principal',
    family: 'Family',
    anyFamily: 'All families',
    noFamily: 'No family',
    state: 'State',
    anyState: 'All states',
    trackingMode: 'Tracking mode',
    anyTrackingMode: 'All modes',
    search: 'Search',
    none: 'No item.',
    create: 'Create an item',
    newTitle: 'New item',
    code: 'Code',
    shortLabel: 'Short label',
    longLabel: 'Long label',
    identity: 'Identity',
    principalLocked: 'The principal no longer changes once saved.',
    states: { draft: 'Draft', active: 'Active', dormant: 'Dormant', obsolete: 'Obsolete' },
    trackingModes: { quantity: 'Quantity', batch: 'Batch', serial: 'Serial' },
    serialBatchTracking: 'Batch tracking',
    trackingWarning: 'This choice becomes final at the first stock movement.',
    trackingLocked: 'A stock movement has been recorded: the tracking mode no longer changes.',
    dates: 'Dates carried by stock',
    tracksExpiryDate: 'Expiry date',
    tracksManufacturingDate: 'Manufacturing date',
    kind: 'Kind of item',
    isKit: 'Kit',
    createdOn: 'Created on',
    stock: 'Stock',
    stockSites: 'Sites',
    packaging: 'Packaging',
    baseLevel: 'Base level',
    addLevel: 'Add a level',
    removeLevel: 'Remove the top level',
    levelName: 'Level label',
    unitsOfLowerLevel: 'Contains (lower level)',
    grossWeight: 'Gross weight (g)',
    length: 'Length (mm)',
    width: 'Width (mm)',
    height: 'Height (mm)',
    topLevelUnits: 'The top level contains {{count}} base unit(s).',
    incomplete: 'Incomplete',
    complete: 'Complete',
    barcodes: 'Barcodes',
    barcode: 'Barcode',
    nature: 'Nature',
    natures: {
      internal: 'Internal code',
      gtin: 'GTIN/EAN',
      supplier: 'Supplier code',
      principal: 'Principal code',
      free: 'Free code',
    },
    onLevel: 'Packaging level',
    wholeItem: 'The item',
    addBarcode: 'Add the barcode',
    noBarcode: 'No barcode.',
    customValues: 'Custom fields',
    required: 'Required',
    noCustomFields: 'This principal has declared no custom field.',
    inactiveField: 'Deactivated field',
    adr: 'ADR classification',
    dangerous: 'Dangerous goods',
    adrClass: 'Class',
    unNumber: 'UN number',
    packingGroup: 'Packing group',
    noPackingGroup: 'No group',
    adrHint: 'Declarative: feeds transport documents, with no storage constraint.',
    value: 'Declared value',
    valueAmount: 'Unit value in cents ({{currency}})',
    noCurrency: 'The principal has no currency: the value waits until one is declared.',
    noValue: 'No value',
    setAt: 'Since',
    clearValue: 'Remove the value',
    kit: 'Kit composition',
    repairBom: 'Repair bill of materials',
    repairBomHint: 'Replaceable components, with no effect on the stock of the described item.',
    component: 'Component',
    quantity: 'Quantity',
    noComponent: 'No component.',
    replacements: 'Substitutions',
    replacementsHint: 'Items that can replace this one: a proposal, never an automatic substitution.',
    replacing: 'Replacement',
    noReplacement: 'No substitution.',
    activation: 'State',
    activate: 'Activate the item',
    missing: {
      requiredCustomFields: 'fill in the required fields',
      completePackaging: 'one complete packaging level',
      barcode: 'one active barcode',
    },
    missingIntro: 'To activate: {{list}}.',
    toDormant: 'Make dormant',
    toObsolete: 'Make obsolete',
    reactivate: 'Reactivate',
    obsoleteWithStock:
      'Obsolete item with {{count}} unit(s) in stock: that stock can still be moved and shipped.',
    choose: 'Choose',
  },
  itemFamily: {
    title: 'Families',
    code: 'Code',
    name: 'Label',
    parent: 'Parent family',
    root: 'None',
    items: 'Items',
    create: 'Create the family',
    none: 'No family.',
  },
  customField: {
    title: 'Custom fields',
    label: 'Label',
    type: 'Type',
    types: { text: 'Text', number: 'Number', date: 'Date', list: 'List of values', boolean: 'Yes or no' },
    listValues: 'List values, comma separated',
    required: 'Required',
    create: 'Declare the field',
    remove: 'Remove',
    used: 'Items',
    none: 'No custom field.',
    deactivated: 'Field deactivated: {{count}} item(s) fill it in, their value stays readable.',
    deleted: 'Field deleted: no item filled it in.',
  },
  session: {
    title: 'Open a session',
    loginName: 'Login name',
    password: 'Password',
    open: 'Open the session',
    close: 'Close the session',
  },
  workstation: {
    label: 'Workstation',
    undeclared: 'Undeclared workstation',
  },
  failure: {
    noResponse:
      'The server is not responding. Check the connection, then try again: nothing will be recorded twice.',
  },
  refusal: {
    principalLocked: 'An item’s principal no longer changes.',
    trackingModeLocked:
      'A stock movement has been recorded: the tracking mode no longer changes. Create a new item.',
    batchTrackingSerialOnly: 'Batch tracking is only declared with serial tracking.',
    kitWithRepairBom: 'An item cannot be both a kit and carry a repair bill of materials.',
    unknownFamily: 'This family does not exist for this principal.',
    barcodeTaken: 'This barcode is already assigned to item {{item}}.',
    invalidCoefficient: 'Each level above the base states how many units of the lower level it contains.',
    barcodeOnRemovedLevel: 'Barcode {{name}} designates this level: it cannot be removed.',
    unknownPackagingLevel: 'This packaging level does not exist.',
    unknownBarcode: 'This barcode does not exist on this item.',
    unknownCustomField: 'This custom field does not exist or is no longer active.',
    invalidCustomValue: 'A value does not suit its field’s type.',
    componentOtherPrincipal: 'A component or substitution does not belong to the item’s principal.',
    notAKit: 'This item is not marked as a kit.',
    kitCycle: 'A kit cannot contain itself: {{cycle}}.',
    currencyMissing: 'The principal has declared no currency.',
    itemActivationIncomplete: 'The item cannot be activated yet: elements are missing.',
    invalidTransition: 'This state change is not possible.',
    familyCycle: 'A family cannot be placed under one of its sub-families.',
    listValuesRequired: 'A list of values carries at least one.',
    fieldTypeLocked: 'This field is already filled in: its type no longer changes.',
    unknownParty: 'This party does not exist.',
    codeRequired: 'This party needs a code.',
    principalMismatch: 'This party does not belong to this principal, or its family does not allow it.',
    anonymizedParty: 'This record is anonymised or merged: it can no longer change.',
    unknownAddress: 'This address does not exist.',
    postalCodeFormat: 'The address is incomplete, or its postal code does not follow the country format.',
    unknownService: 'This service does not exist.',
    unknownAccount: 'This account does not exist.',
    notEndCustomers: 'Only two end customer records can be merged or anonymised.',
    alreadyMerged: 'One of the two records has already been merged.',
    samePartyTwice: 'Choose two different records.',
    openFlows: 'This end customer has an open flow: anonymisation waits for it to close.',
    unknownWorkstation: 'This workstation does not exist.',
    codeTaken: 'This code is already in use.',
    codeLocked: 'The code can no longer change: the site has already been used.',
    unknownTimeZone: 'This time zone does not exist.',
    activationIncomplete: 'The site cannot be activated yet: it lacks an address or a zone.',
    activityRemaining: 'Stock or open flows remain to be settled.',
    overlappingRanges: 'Two opening ranges of the same day overlap, or a range closes before it opens.',
    unknownZone: 'This zone does not exist.',
    principalRequired: 'A single-principal zone names its reserved principal.',
    foreignStock: 'The zone holds stock of another principal: it cannot be reserved.',
    internalPrincipal: 'The internal principal cannot be deactivated.',
    unknownRole: 'This role does not exist.',
    nameTaken: 'This name is already in use.',
    lastRoleAdministrator: 'At least one active user must keep role administration.',
    roleHeld: 'This role is still held by users.',
    unknownUser: 'This user does not exist.',
    loginNameTaken: 'This login name is already in use.',
    passwordRequired: 'A new user receives a password.',
    unknownTeam: 'This team does not exist or is no longer active.',
    teamOutsideSites: 'The team belongs to a site the user is not attached to.',
    hierarchyCycle: 'This reporting line would place the user under someone they supervise.',
    siteRequired: 'A user is activated with at least one site.',
    ownExecutionSites: 'No one changes their own execution sites.',
    executionOutsideSites: 'An execution site is chosen among the attached sites.',
    leadOutsideSite: 'The team lead is not attached to the team’s site.',
    teamHasMembers: 'The team still has members: move them before deactivating it.',
    unknownObjectType: 'This object type has no numbering scheme.',
    numberingNotUnique: 'This composition does not guarantee unique identifiers.',
    unknownDock: 'This dock does not exist or is no longer active.',
    dockOccupied: 'Dock {{dock}} is already occupied by a vehicle.',
    unknownCarrier: 'This carrier does not exist or is no longer active.',
    unknownPrincipal: 'This principal does not exist or is no longer active.',
    unknownSupplier: 'This supplier does not belong to the principal, or is no longer active.',
    unknownItem: 'This item does not exist, does not belong to the principal, or can no longer be received.',
    duplicateItem: 'An item appears on two lines.',
    invalidInput: 'The input is incomplete or invalid.',
    notAuthenticated: 'You must sign in.',
    permissionDenied: 'You do not have permission for this gesture.',
    outOfScope: 'This object is outside your scope.',
    undeclaredWorkstation: 'This workstation is not declared: no gesture is possible.',
    editLockHeldByOther: '{{holder}} holds the edit lock.',
    invalidCredentials: 'Incorrect login name or password.',
    tooManyAttempts: 'Too many attempts: try again in a few minutes.',
    workstationNameTaken: 'A workstation is already named {{name}}.',
    unknownSite: 'This site does not exist.',
  },
};
