/**
 * Libellés français, langue par défaut (RG-EXI-054). Les textes suivent le glossaire ;
 * aucun libellé n'est écrit en dur dans un écran (fiche 0025, règle 4).
 */
export const fr = {
  application: {
    name: 'Cairn WMS',
  },
  shell: {
    home: 'Accueil',
    dismiss: 'Masquer',
    siteTime: 'Heure locale du site',
  },
  navigation: {
    office: 'Bureau',
    receptions: 'Réceptions',
    items: 'Références',
    arrivalsInProgress: '{{count}} arrivage(s) en cours',
  },
  expectedReceipt: {
    openList: 'Attendus ouverts',
    create: 'Saisir un attendu',
    newTitle: 'Nouvel attendu',
    title: 'Attendu {{number}}',
    number: 'Attendu',
    principal: 'Donneur d’ordre',
    supplier: 'Fournisseur',
    expectedArrivalDate: 'Arrivée prévue',
    lineCount: 'Lignes',
    state: 'État',
    states: { open: 'Ouvert', settled: 'Soldé', cancelled: 'Annulé' },
    lines: 'Lignes de l’attendu',
    item: 'Référence',
    shortLabel: 'Libellé',
    quantity: 'Quantité',
    expectedQuantity: 'Attendu',
    servedQuantity: 'Servi',
    remainingQuantity: 'Solde',
    addLine: 'Ajouter une ligne',
    removeLine: 'Retirer la ligne',
    save: 'Enregistrer l’attendu',
    choose: 'Choisir…',
    none: 'Aucun attendu ouvert sur ce site.',
  },
  dock: {
    list: 'Quais',
    title: 'Quai {{code}}',
    free: 'Libre',
    occupied: 'Occupé',
    noVehicle: 'Aucun véhicule',
    arrival: 'Arrivage · {{vehicle}}',
    openedBy: 'Ouvert par {{name}} à {{time}}',
    occupiedSince: 'Occupé depuis',
  },
  arrival: {
    open: 'Ouvrir un arrivage',
    title: 'Nouvel arrivage au quai {{code}}',
    vehicle: 'Véhicule',
    carrier: 'Transporteur',
    noCarrier: 'Sans transporteur',
    submit: 'Ouvrir l’arrivage',
    cancel: 'Annuler',
  },
  common: {
    save: 'Enregistrer',
    cancel: 'Annuler',
    add: 'Ajouter',
    remove: 'Retirer',
    edit: 'Modifier',
    create: 'Créer',
    activate: 'Activer',
    deactivate: 'Désactiver',
    active: 'Actif',
    inactive: 'Inactif',
    none: 'Aucun',
    saved: 'Enregistré.',
    yes: 'Oui',
    no: 'Non',
    export: 'Exporter',
  },
  administration: {
    group: 'Administration',
    settings: 'Paramétrage',
    usersAndTeams: 'Utilisateurs et équipes',
    principals: 'Donneurs d’ordre',
    sites: 'Sites',
    numbering: 'Numérotation',
    provider: 'Prestataire',
    workstations: 'Postes',
    users: 'Utilisateurs',
    roles: 'Rôles',
    teams: 'Équipes',
    remaining: 'Reste à solder : {{detail}}.',
  },
  site: {
    create: 'Créer un site',
    newTitle: 'Nouveau site',
    title: 'Site {{code}}',
    code: 'Code',
    name: 'Libellé',
    city: 'Ville',
    zoneCount: 'Zones',
    state: 'État',
    timeZone: 'Fuseau horaire',
    addressLine1: 'Adresse',
    addressLine2: 'Complément d’adresse',
    postalCode: 'Code postal',
    countryCode: 'Pays',
    codeLocked: 'Le code ne change plus : le site a déjà servi.',
    activation: 'Activation',
    missing: 'Pour activer le site, il manque : {{missing}}.',
    missingAddress: 'une adresse',
    missingZone: 'une zone active',
    ready: 'Le site peut être activé.',
    calendar: 'Calendrier',
    calendarEmpty:
      'Sans plage d’ouverture, le site est réputé ouvert en continu : les délais n’y sont pas qualifiés.',
    opensAt: 'Ouverture',
    closesAt: 'Fermeture',
    addRange: 'Ajouter une plage',
    closed: 'Fermé',
    closures: 'Jours fériés et fermetures',
    day: 'Date',
    label: 'Motif',
    kind: 'Nature',
    kinds: { publicHoliday: 'Jour férié', exceptional: 'Fermeture exceptionnelle' },
    addClosure: 'Ajouter une fermeture',
    addPublicHolidays: 'Ajouter les jours fériés de {{year}}',
    noClosure: 'Aucun jour fermé.',
    zones: 'Zones',
    addZone: 'Ajouter une zone',
    noZone: 'Aucune zone : ajoutez-en une pour pouvoir activer le site.',
    purpose: 'Vocation',
    cohabitation: 'Cohabitation',
    reservedFor: 'Donneur d’ordre réservataire',
    list: 'Sites',
  },
  weekday: {
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
  },
  zonePurpose: {
    storage: 'Stockage',
    picking: 'Prélèvement',
    receiving: 'Réception',
    shipping: 'Expédition',
    preparation: 'Préparation',
    consolidation: 'Consolidation',
    quarantine: 'Quarantaine',
    dispute: 'Litige',
    workshop: 'Atelier',
    destruction: 'Destruction',
    virtual: 'Virtuel',
  },
  cohabitation: { single: 'Mono-donneur d’ordre', shared: 'Mutualisée' },
  principalAdmin: {
    list: 'Donneurs d’ordre',
    create: 'Créer un donneur d’ordre',
    newTitle: 'Nouveau donneur d’ordre',
    code: 'Code',
    name: 'Libellé',
    group: 'Groupe',
    internal: 'Interne',
    email: 'Adresse électronique',
    phone: 'Téléphone',
    state: 'État',
    address: 'Coordonnées',
    currency: 'Devise (ISO 4217)',
    currencyTitle: 'Devise',
    currencyHint:
      'Devise unique du donneur d’ordre, dans laquelle s’expriment les valeurs déclarées de ses références.',
  },
  role: {
    list: 'Rôles',
    create: 'Composer un rôle',
    newTitle: 'Nouveau rôle',
    name: 'Libellé',
    nature: 'Nature',
    natures: { operational: 'Opérationnelle', administrative: 'Administrative' },
    natureHint:
      'Opérationnel, un rôle transmet à l’encadrant ses droits d’exécution ; administratif, il ne transmet que la visibilité.',
    template: 'Modèle',
    holders: 'Porteurs',
    permissions: 'Permissions',
    heldBy: 'Ce rôle est porté par {{count}} utilisateur(s) : la modification vaut pour chacun.',
    delete: 'Supprimer le rôle',
  },
  permissionDomain: {
    catalog: 'Référentiel produit',
    partners: 'Tiers',
    reception: 'Réception',
    settings: 'Paramétrage',
  },
  permission: {
    managePrincipalParties: 'Gérer les fournisseurs et les clients finaux',
    mergeEndCustomers: 'Fusionner deux fiches de client final',
    anonymizeEndCustomers: 'Anonymiser un client final',
    administerProviderParties: 'Administrer les transporteurs et les sous-traitants',
    createExpectedReceipt: 'Saisir un attendu',
    openInboundArrival: 'Ouvrir un arrivage',
    administerProvider: 'Administrer le prestataire',
    administerSites: 'Administrer les sites, calendriers et zones',
    administerPrincipals: 'Administrer les donneurs d’ordre',
    administerRoles: 'Composer les rôles',
    administerUsers: 'Administrer les utilisateurs',
    administerExecutionSites: 'Fixer les sites d’exécution',
    administerTeams: 'Administrer les équipes',
    administerNumbering: 'Composer la numérotation',
    declareWorkstation: 'Déclarer et révoquer les postes',
    manageItems: 'Gérer les références et leurs familles',
    manageCustomFields: 'Déclarer les champs personnalisés',
    createDraftItem: 'Créer une référence à la volée',
  },
  user: {
    list: 'Utilisateurs',
    create: 'Créer un utilisateur',
    newTitle: 'Nouvel utilisateur',
    identity: 'Identité',
    displayName: 'Nom',
    loginName: 'Identifiant de connexion',
    email: 'Adresse électronique',
    password: 'Mot de passe',
    passwordHint: 'Douze caractères au moins. À la modification, laissez vide pour garder l’actuel.',
    roles: 'Rôles',
    sites: 'Sites',
    team: 'Équipe',
    reportsTo: 'Relève de',
    executionSites: 'Sites d’exécution',
    executionHint: 'Parmi ses sites, ceux où il agit ; ailleurs il consulte.',
    ownExecution: 'Nul ne modifie ses propres sites d’exécution.',
    restrictions: 'Restrictions par donneur d’ordre',
    restrictionsHint:
      'Exception : sans restriction, l’utilisateur voit tous les donneurs d’ordre de ses sites.',
    effectivePermissions: 'Permissions effectives',
    state: 'État',
    noSiteWarning: 'Rattaché à aucun site, cet utilisateur ne voit aucune donnée opérationnelle.',
  },
  team: {
    list: 'Équipes',
    create: 'Créer une équipe',
    newTitle: 'Nouvelle équipe',
    name: 'Nom',
    site: 'Site',
    lead: 'Encadrant',
    noLead: 'Sans encadrant',
    members: 'Membres',
    state: 'État',
  },
  numbering: {
    list: 'Schémas de numérotation',
    objectType: 'Type d’objet',
    composition: 'Composition',
    example: 'Exemple',
    segment: 'Segment',
    width: 'Chiffres',
    value: 'Texte',
    addSegment: 'Ajouter un segment',
    kinds: {
      literal: 'Texte fixe',
      site: 'Code site',
      principal: 'Code donneur d’ordre',
      year: 'Année',
      month: 'Mois',
      counter: 'Compteur',
    },
    problems: {
      leadingLiteralRequired: 'Le schéma commence par un texte fixe, qui dit le type d’objet.',
      leadingLiteralTaken: 'Ce texte de tête est déjà celui d’un autre type d’objet, ou le préfixe.',
      singleCounterRequired: 'Le schéma porte un compteur, un seul.',
      yearRequiredForMonth: 'Le mois s’accompagne de l’année.',
      separatorRequired: 'Deux codes de longueur variable se séparent par un texte fixe.',
    },
    objectTypes: { ExpectedReceipt: 'Attendu' },
  },
  provider: {
    title: 'Prestataire',
    name: 'Nom du prestataire',
    unnamed: 'Le prestataire n’a pas encore de nom.',
  },
  workstationAdmin: {
    list: 'Postes déclarés',
    name: 'Nom du poste',
    site: 'Site',
    state: 'État',
    revoked: 'Révoqué',
    revoke: 'Révoquer',
    declare: 'Déclarer ce navigateur comme poste',
    declareTitle: 'Ce navigateur',
    current: 'Ce navigateur est le poste « {{name}} ».',
    undeclared: 'Ce navigateur n’est pas un poste déclaré : aucun geste n’y est possible.',
  },
  siteSelector: { label: 'Site' },
  principalSelector: { label: 'Donneur d’ordre du contexte de travail', placeholder: 'Donneur d’ordre' },
  remainingKind: { expectedReceipts: 'attendu(s) ouvert(s)', inboundArrivals: 'arrivage(s) en cours' },
  party: {
    menu: 'Tiers',
    principal: 'Donneur d’ordre',
    suppliers: 'Fournisseurs',
    endCustomers: 'Clients finaux',
    carriers: 'Transporteurs',
    subcontractors: 'Sous-traitants',
    duplicates: 'Doublons potentiels',
    schedule: 'Échéances d’anonymisation',
    search: 'Rechercher',
    create: 'Créer',
    code: 'Code',
    codeHint: 'Laissez vide pour une clé générée.',
    name: 'Raison sociale ou nom',
    email: 'Adresse électronique',
    phone: 'Téléphone',
    city: 'Ville',
    state: 'État',
    toComplete: 'À compléter',
    anonymized: 'Client final anonymisé',
    merged: 'Fiche absorbée',
    readOnly: 'Lecture seule : cette fiche a été absorbée par une fusion ou anonymisée.',
    none: 'Aucun tiers.',
    nature: 'Nature de la prestation',
    natures: {
      repair: 'Réparation',
      destruction: 'Destruction',
      recycling: 'Recyclage',
      refurbishment: 'Reconditionnement',
      other: 'Autre',
    },
    certificate: 'Produit un certificat de destruction',
    identity: 'Identité',
    families: {
      supplier: 'Fournisseur',
      endCustomer: 'Client final',
      carrier: 'Transporteur',
      subcontractor: 'Sous-traitant',
    },
  },
  address: {
    title: 'Adresses',
    add: 'Ajouter une adresse',
    usage: 'Usage',
    usages: { delivery: 'Livraison', return: 'Retour', billing: 'Facturation', headOffice: 'Siège' },
    isDefault: 'Par défaut',
    recipient: 'Destinataire',
    line1: 'Adresse',
    line2: 'Complément',
    postalCode: 'Code postal',
    city: 'Ville',
    countryCode: 'Pays',
    none: 'Aucune adresse.',
    postalFormat: 'Format attendu pour ce pays : {{example}}.',
  },
  endCustomer: {
    lastFlow: 'Dernier flux',
    noFlow: 'Aucun flux',
    dueOn: 'Échéance d’anonymisation',
    noRetention: 'Pas de durée de conservation déclarée : aucune anonymisation automatique.',
    history: 'Historique',
    historyEmpty: 'Aucune commande, expédition, retour, dossier ni litige.',
    counters: 'Commandes · retours · dossiers · litiges',
    anonymize: 'Anonymiser',
    anonymizeTitle: 'Anonymiser ce client final',
    anonymizeWarning:
      'L’anonymisation est irréversible : nom, adresses, téléphone et adresse électronique seront effacés. Les flux restent consultables.',
    reason: 'Motif',
    confirm: 'Anonymiser définitivement',
    merge: 'Fusionner avec une autre fiche',
    mergeTitle: 'Fusionner deux fiches',
    other: 'Autre fiche',
    kept: 'Fiche conservée',
    absorbed: 'Fiche absorbée',
    takeFrom: 'Valeur retenue',
    mergeWarning: 'La fusion est définitive : la fiche absorbée reste consultable en lecture seule.',
    confirmMerge: 'Fusionner définitivement',
    reasons: { name: 'Même nom', email: 'Même adresse électronique', phone: 'Même téléphone' },
    compare: 'Comparer',
  },
  schedule: {
    retention: 'Conservation (mois)',
    dueSoon: 'Échéance sous 30 jours',
    postponed: 'Reportés (flux en cours)',
    anonymized: 'Anonymisés sur 30 jours',
    missing: 'Non déclarée',
  },
  carrier: {
    services: 'Services',
    addService: 'Ajouter un service',
    serviceCode: 'Code',
    serviceName: 'Libellé',
    direction: 'Sens',
    directions: { outbound: 'Aller', return: 'Retour', both: 'Aller et retour' },
    maxWeightGrams: 'Poids maximum (g)',
    maxLengthMm: 'Longueur maximum (mm)',
    maxWidthMm: 'Largeur maximum (mm)',
    maxHeightMm: 'Hauteur maximum (mm)',
    maxDimensionSumMm: 'Somme des dimensions maximum (mm)',
    maxInsuredValueCents: 'Valeur assurée maximum (centimes)',
    dangerousGoods: 'Accepte les matières dangereuses',
    label: 'Étiquette',
    labels: {
      none: 'Aucune',
      carrier: 'Générée par le transporteur',
      provider: 'Générée par le prestataire',
    },
    leadTimeDays: 'Délai annoncé (jours ouvrés)',
    accounts: 'Comptes',
    addAccount: 'Ajouter un compte',
    accountNumber: 'Numéro de compte',
    contractReference: 'Référence du contrat',
    accountPrincipal: 'Donneur d’ordre',
    providerAccount: 'Compte du prestataire',
  },
  retention: {
    title: 'Conservation des données des clients finaux',
    months: 'Durée (mois)',
    hint: 'À compter du dernier flux. Vide : aucune anonymisation automatique.',
  },
  item: {
    menu: 'Références',
    list: 'Références',
    all: 'Toutes',
    toComplete: 'Références à compléter',
    toCompleteHint: 'Brouillons, du plus ancien au plus récent, avec le stock qu’ils immobilisent.',
    toCompleteTab: 'À compléter',
    principal: 'Donneur d’ordre',
    family: 'Famille',
    anyFamily: 'Toutes les familles',
    noFamily: 'Sans famille',
    state: 'État',
    anyState: 'Tous les états',
    trackingMode: 'Axe de gestion',
    anyTrackingMode: 'Tous les axes',
    search: 'Rechercher',
    none: 'Aucune référence.',
    create: 'Créer une référence',
    newTitle: 'Nouvelle référence',
    code: 'Code',
    shortLabel: 'Libellé court',
    longLabel: 'Libellé long',
    identity: 'Identité',
    principalLocked: 'Le donneur d’ordre ne change plus après l’enregistrement.',
    states: { draft: 'Brouillon', active: 'Active', dormant: 'En sommeil', obsolete: 'Obsolète' },
    trackingModes: { quantity: 'Quantitatif', batch: 'Lot', serial: 'Série' },
    serialBatchTracking: 'Suivi par lot',
    trackingWarning: 'Ce choix devient définitif dès le premier mouvement de stock.',
    trackingLocked: 'Un mouvement de stock a été enregistré : l’axe de gestion ne change plus.',
    dates: 'Dates portées par le stock',
    tracksExpiryDate: 'Date de péremption',
    tracksManufacturingDate: 'Date de fabrication',
    kind: 'Nature de la référence',
    isKit: 'Kit',
    createdOn: 'Créée le',
    stock: 'Stock',
    stockSites: 'Sites',
    packaging: 'Conditionnements',
    baseLevel: 'Niveau de base',
    addLevel: 'Ajouter un niveau',
    removeLevel: 'Retirer le niveau le plus haut',
    levelName: 'Libellé du niveau',
    unitsOfLowerLevel: 'Contient (niveau inférieur)',
    grossWeight: 'Poids brut (g)',
    length: 'Longueur (mm)',
    width: 'Largeur (mm)',
    height: 'Hauteur (mm)',
    topLevelUnits: 'Le niveau le plus haut contient {{count}} unité(s) de base.',
    incomplete: 'Incomplet',
    complete: 'Complet',
    barcodes: 'Identifiants scannables',
    barcode: 'Identifiant',
    nature: 'Nature',
    natures: {
      internal: 'Code interne',
      gtin: 'GTIN/EAN',
      supplier: 'Code fournisseur',
      principal: 'Code donneur d’ordre',
      free: 'Code libre',
    },
    onLevel: 'Niveau de conditionnement',
    wholeItem: 'La référence',
    addBarcode: 'Ajouter l’identifiant',
    noBarcode: 'Aucun identifiant.',
    customValues: 'Champs personnalisés',
    required: 'Obligatoire',
    noCustomFields: 'Ce donneur d’ordre n’a déclaré aucun champ personnalisé.',
    inactiveField: 'Champ désactivé',
    adr: 'Classement ADR',
    dangerous: 'Matière dangereuse',
    adrClass: 'Classe',
    unNumber: 'Numéro ONU',
    packingGroup: 'Groupe d’emballage',
    noPackingGroup: 'Sans groupe',
    adrHint: 'Déclaratif : alimente les documents de transport, sans contrainte de stockage.',
    value: 'Valeur déclarée',
    valueAmount: 'Valeur unitaire ({{currency}})',
    noCurrency: 'Le donneur d’ordre n’a pas de devise : la valeur attend qu’il en déclare une.',
    noValue: 'Sans valeur',
    setAt: 'Depuis le',
    clearValue: 'Retirer la valeur',
    kit: 'Composition du kit',
    repairBom: 'Nomenclature de réparation',
    repairBomHint: 'Composants remplaçables, sans effet sur le stock de la référence décrite.',
    component: 'Composant',
    quantity: 'Quantité',
    noComponent: 'Aucun composant.',
    replacements: 'Équivalences',
    replacementsHint:
      'Références qui peuvent remplacer celle-ci : une proposition, jamais une substitution automatique.',
    replacing: 'Remplaçante',
    noReplacement: 'Aucune équivalence.',
    activation: 'État',
    activate: 'Activer la référence',
    missing: {
      requiredCustomFields: 'renseigner les champs obligatoires',
      completePackaging: 'un niveau de conditionnement complet',
      barcode: 'un identifiant scannable actif',
    },
    missingIntro: 'Pour activer : {{list}}.',
    toDormant: 'Mettre en sommeil',
    toObsolete: 'Rendre obsolète',
    reactivate: 'Réactiver',
    obsoleteWithStock:
      'Référence obsolète avec {{count}} unité(s) en stock : ce stock reste mouvementable et sortant.',
    choose: 'Choisir',
  },
  itemFamily: {
    title: 'Familles',
    code: 'Code',
    name: 'Libellé',
    parent: 'Famille parente',
    root: 'Aucune',
    items: 'Références',
    create: 'Créer la famille',
    none: 'Aucune famille.',
  },
  customField: {
    title: 'Champs personnalisés',
    label: 'Libellé',
    type: 'Type',
    types: { text: 'Texte', number: 'Nombre', date: 'Date', list: 'Liste de valeurs', boolean: 'Oui ou non' },
    listValues: 'Valeurs de la liste, séparées par des virgules',
    required: 'Obligatoire',
    create: 'Déclarer le champ',
    remove: 'Retirer',
    used: 'Références',
    none: 'Aucun champ personnalisé.',
    deactivated: 'Champ désactivé : {{count}} référence(s) le renseignent, leur valeur reste lisible.',
    deleted: 'Champ supprimé : aucune référence ne le renseignait.',
  },
  search: {
    label: 'Rechercher ou scanner',
    placeholder: 'Rechercher ou scanner un code…',
    title: 'Recherche',
    results: 'Résultats',
    unknown: 'Aucun objet ne correspond à « {{text}} » : ce code n’est pas connu.',
    object: 'Objet',
    code: 'Code',
    name: 'Nom ou libellé',
    principal: 'Donneur d’ordre',
    site: 'Site',
    types: { item: 'Référence', party: 'Tiers', expectedReceipt: 'Attendu' },
    outOfScope: 'Hors de votre périmètre',
    inactiveCode: 'Identifiant désactivé',
  },
  session: {
    otherLanguage: 'English',
    title: 'Ouvrir une session',
    loginName: 'Identifiant de connexion',
    password: 'Mot de passe',
    open: 'Ouvrir la session',
    close: 'Fermer la session',
  },
  workstation: {
    label: 'Poste',
    undeclared: 'Poste non déclaré',
  },
  failure: {
    noResponse:
      'Le serveur ne répond pas. Vérifiez la connexion, puis recommencez : rien ne sera enregistré deux fois.',
  },
  refusal: {
    principalLocked: 'Le donneur d’ordre d’une référence ne change plus.',
    trackingModeLocked:
      'Un mouvement de stock a été enregistré : l’axe de gestion ne change plus. Créez une nouvelle référence.',
    batchTrackingSerialOnly: 'Le suivi par lot ne se déclare qu’en gestion série.',
    kitWithRepairBom:
      'Une référence ne peut pas être à la fois un kit et porter une nomenclature de réparation.',
    unknownFamily: 'Cette famille n’existe pas chez ce donneur d’ordre.',
    barcodeTaken: 'Cet identifiant est déjà attribué à la référence {{item}}.',
    invalidCoefficient:
      'Chaque niveau au-dessus de la base dit combien d’unités du niveau inférieur il contient.',
    barcodeOnRemovedLevel: 'L’identifiant {{name}} désigne ce niveau : il ne peut pas être retiré.',
    unknownPackagingLevel: 'Ce niveau de conditionnement n’existe pas.',
    unknownBarcode: 'Cet identifiant n’existe pas sur cette référence.',
    unknownCustomField: 'Ce champ personnalisé n’existe pas ou n’est plus actif.',
    invalidCustomValue: 'Une valeur ne convient pas au type de son champ.',
    componentOtherPrincipal:
      'Un composant ou une équivalence n’appartient pas au donneur d’ordre de la référence.',
    notAKit: 'Cette référence n’est pas marquée comme kit.',
    kitCycle: 'Un kit ne peut pas se contenir lui-même : {{cycle}}.',
    currencyMissing: 'Le donneur d’ordre n’a pas déclaré de devise.',
    itemActivationIncomplete: 'La référence ne peut pas encore être activée : il lui manque des éléments.',
    invalidTransition: 'Ce changement d’état n’est pas possible.',
    familyCycle: 'Une famille ne se range pas sous l’une de ses sous-familles.',
    listValuesRequired: 'Une liste de valeurs en porte au moins une.',
    fieldTypeLocked: 'Ce champ est déjà renseigné : son type ne change plus.',
    unknownParty: 'Ce tiers n’existe pas.',
    codeRequired: 'Ce tiers porte un code.',
    principalMismatch: 'Ce tiers n’appartient pas à ce donneur d’ordre, ou sa famille ne le permet pas.',
    anonymizedParty: 'Cette fiche est anonymisée ou absorbée : elle ne se modifie plus.',
    unknownAddress: 'Cette adresse n’existe pas.',
    postalCodeFormat: 'L’adresse est incomplète, ou son code postal ne suit pas le format du pays.',
    unknownService: 'Ce service n’existe pas.',
    unknownAccount: 'Ce compte n’existe pas.',
    notEndCustomers: 'Seules deux fiches de client final se fusionnent ou s’anonymisent.',
    alreadyMerged: 'Une des deux fiches a déjà été absorbée par une fusion.',
    samePartyTwice: 'Choisissez deux fiches différentes.',
    openFlows: 'Ce client final porte un flux en cours : l’anonymisation attend sa clôture.',
    unknownWorkstation: 'Ce poste n’existe pas.',
    codeTaken: 'Ce code est déjà employé.',
    codeLocked: 'Le code ne change plus : le site a déjà servi.',
    unknownTimeZone: 'Ce fuseau horaire n’existe pas.',
    activationIncomplete: 'Le site ne peut pas encore être activé : il lui manque une adresse ou une zone.',
    activityRemaining: 'Il reste du stock ou des flux en cours à solder.',
    overlappingRanges:
      'Deux plages d’ouverture d’un même jour se chevauchent, ou une plage ferme avant d’ouvrir.',
    unknownZone: 'Cette zone n’existe pas.',
    principalRequired: 'Une zone mono-donneur d’ordre désigne son donneur d’ordre réservataire.',
    foreignStock: 'La zone porte du stock d’un autre donneur d’ordre : elle ne peut pas lui être réservée.',
    internalPrincipal: 'Le donneur d’ordre interne ne se désactive pas.',
    unknownRole: 'Ce rôle n’existe pas.',
    nameTaken: 'Ce nom est déjà employé.',
    lastRoleAdministrator: 'Au moins un utilisateur actif doit garder l’administration des rôles.',
    roleHeld: 'Ce rôle est encore porté par des utilisateurs.',
    unknownUser: 'Cet utilisateur n’existe pas.',
    loginNameTaken: 'Cet identifiant de connexion est déjà employé.',
    passwordRequired: 'Un nouvel utilisateur reçoit un mot de passe.',
    unknownTeam: 'Cette équipe n’existe pas ou n’est plus active.',
    teamOutsideSites: 'L’équipe appartient à un site où l’utilisateur n’est pas rattaché.',
    hierarchyCycle: 'Ce rattachement placerait l’utilisateur sous quelqu’un qu’il encadre.',
    siteRequired: 'Un utilisateur s’active avec au moins un site.',
    ownExecutionSites: 'Nul ne modifie ses propres sites d’exécution.',
    executionOutsideSites: 'Un site d’exécution est choisi parmi les sites de rattachement.',
    leadOutsideSite: 'L’encadrant n’est pas rattaché au site de l’équipe.',
    teamHasMembers: 'L’équipe a encore des membres : replacez-les avant de la désactiver.',
    unknownObjectType: 'Ce type d’objet n’a pas de schéma de numérotation.',
    numberingNotUnique: 'Cette composition ne garantit pas l’unicité des identifiants.',
    unknownDock: 'Ce quai n’existe pas ou n’est plus actif.',
    dockOccupied: 'Le quai {{dock}} est déjà occupé par un véhicule.',
    unknownCarrier: 'Ce transporteur n’existe pas ou n’est plus actif.',
    unknownPrincipal: 'Ce donneur d’ordre n’existe pas ou n’est plus actif.',
    unknownSupplier: 'Ce fournisseur n’appartient pas au donneur d’ordre, ou n’est plus actif.',
    unknownItem:
      'Cette référence n’existe pas, n’appartient pas au donneur d’ordre, ou ne peut plus être reçue.',
    duplicateItem: 'Une référence figure sur deux lignes.',
    invalidInput: 'La saisie est incomplète ou invalide.',
    notAuthenticated: 'Vous devez vous connecter.',
    permissionDenied: 'Vous n’avez pas la permission de faire ce geste.',
    outOfScope: 'Cet objet est hors de votre périmètre.',
    undeclaredWorkstation: 'Ce poste n’est pas déclaré : aucun geste n’est possible.',
    editLockHeldByOther: '{{holder}} a la main.',
    invalidCredentials: 'Identifiant de connexion ou mot de passe incorrect.',
    tooManyAttempts: 'Trop de tentatives : réessayez dans quelques minutes.',
    workstationNameTaken: 'Un poste porte déjà le nom {{name}}.',
    unknownSite: 'Ce site n’existe pas.',
  },
} as const;

type Widen<T> = { readonly [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };

/** Forme que tout catalogue de langue doit avoir : les mêmes clés que le français. */
export type LabelCatalog = Widen<typeof fr>;
