/**
 * Libellés français, langue par défaut (RG-EXI-054). Les textes suivent le glossaire ;
 * aucun libellé n'est écrit en dur dans un écran (fiche 0025, règle 4).
 */
export const fr = {
  application: {
    name: 'Cairn WMS',
  },
  shell: {
    home: 'Accueil',
    dismiss: 'Masquer',
  },
  navigation: {
    office: 'Bureau',
    receptions: 'Réceptions',
  },
  expectedReceipt: {
    openList: 'Attendus ouverts',
    create: 'Saisir un attendu',
    newTitle: 'Nouvel attendu',
    title: 'Attendu {{number}}',
    number: 'Attendu',
    principal: 'Donneur d’ordre',
    supplier: 'Fournisseur',
    expectedArrivalDate: 'Arrivée prévue',
    lineCount: 'Lignes',
    state: 'État',
    states: { open: 'Ouvert', settled: 'Soldé', cancelled: 'Annulé' },
    lines: 'Lignes de l’attendu',
    item: 'Référence',
    shortLabel: 'Libellé',
    quantity: 'Quantité',
    expectedQuantity: 'Attendu',
    servedQuantity: 'Servi',
    remainingQuantity: 'Solde',
    addLine: 'Ajouter une ligne',
    removeLine: 'Retirer la ligne',
    save: 'Enregistrer l’attendu',
    choose: 'Choisir…',
    none: 'Aucun attendu ouvert sur ce site.',
  },
  dock: {
    list: 'Quais',
    title: 'Quai {{code}}',
    free: 'Libre',
    occupied: 'Occupé',
    noVehicle: 'Aucun véhicule',
    arrival: 'Arrivage · {{vehicle}}',
    openedBy: 'Ouvert par {{name}} à {{time}}',
    occupiedSince: 'Occupé depuis',
  },
  arrival: {
    open: 'Ouvrir un arrivage',
    title: 'Nouvel arrivage au quai {{code}}',
    vehicle: 'Véhicule',
    carrier: 'Transporteur',
    noCarrier: 'Sans transporteur',
    submit: 'Ouvrir l’arrivage',
    cancel: 'Annuler',
  },
  session: {
    title: 'Ouvrir une session',
    loginName: 'Identifiant de connexion',
    password: 'Mot de passe',
    open: 'Ouvrir la session',
    close: 'Fermer la session',
  },
  workstation: {
    label: 'Poste',
    undeclared: 'Poste non déclaré',
  },
  failure: {
    noResponse:
      'Le serveur ne répond pas. Vérifiez la connexion, puis recommencez : rien ne sera enregistré deux fois.',
  },
  refusal: {
    codeTaken: 'Ce code est déjà employé.',
    codeLocked: 'Le code ne change plus : le site a déjà servi.',
    unknownTimeZone: 'Ce fuseau horaire n’existe pas.',
    activationIncomplete: 'Le site ne peut pas encore être activé : il lui manque une adresse ou une zone.',
    activityRemaining: 'Il reste du stock ou des flux en cours à solder.',
    overlappingRanges:
      'Deux plages d’ouverture d’un même jour se chevauchent, ou une plage ferme avant d’ouvrir.',
    unknownZone: 'Cette zone n’existe pas.',
    principalRequired: 'Une zone mono-donneur d’ordre désigne son donneur d’ordre réservataire.',
    foreignStock: 'La zone porte du stock d’un autre donneur d’ordre : elle ne peut pas lui être réservée.',
    internalPrincipal: 'Le donneur d’ordre interne ne se désactive pas.',
    unknownRole: 'Ce rôle n’existe pas.',
    nameTaken: 'Ce nom est déjà employé.',
    lastRoleAdministrator: 'Au moins un utilisateur actif doit garder l’administration des rôles.',
    roleHeld: 'Ce rôle est encore porté par des utilisateurs.',
    unknownUser: 'Cet utilisateur n’existe pas.',
    loginNameTaken: 'Cet identifiant de connexion est déjà employé.',
    passwordRequired: 'Un nouvel utilisateur reçoit un mot de passe.',
    unknownTeam: 'Cette équipe n’existe pas ou n’est plus active.',
    teamOutsideSites: 'L’équipe appartient à un site où l’utilisateur n’est pas rattaché.',
    hierarchyCycle: 'Ce rattachement placerait l’utilisateur sous quelqu’un qu’il encadre.',
    siteRequired: 'Un utilisateur s’active avec au moins un site.',
    ownExecutionSites: 'Nul ne modifie ses propres sites d’exécution.',
    executionOutsideSites: 'Un site d’exécution est choisi parmi les sites de rattachement.',
    leadOutsideSite: 'L’encadrant n’est pas rattaché au site de l’équipe.',
    teamHasMembers: 'L’équipe a encore des membres : replacez-les avant de la désactiver.',
    unknownObjectType: 'Ce type d’objet n’a pas de schéma de numérotation.',
    numberingNotUnique: 'Cette composition ne garantit pas l’unicité des identifiants.',
    unknownDock: 'Ce quai n’existe pas ou n’est plus actif.',
    dockOccupied: 'Le quai {{dock}} est déjà occupé par un véhicule.',
    unknownCarrier: 'Ce transporteur n’existe pas ou n’est plus actif.',
    unknownPrincipal: 'Ce donneur d’ordre n’existe pas ou n’est plus actif.',
    unknownSupplier: 'Ce fournisseur n’appartient pas au donneur d’ordre, ou n’est plus actif.',
    unknownItem: 'Une référence n’appartient pas au donneur d’ordre, ou ne peut plus être reçue.',
    duplicateItem: 'Une référence figure sur deux lignes.',
    invalidInput: 'La saisie est incomplète ou invalide.',
    notAuthenticated: 'Vous devez vous connecter.',
    permissionDenied: 'Vous n’avez pas la permission de faire ce geste.',
    outOfScope: 'Cet objet est hors de votre périmètre.',
    undeclaredWorkstation: 'Ce poste n’est pas déclaré : aucun geste n’est possible.',
    editLockHeldByOther: '{{holder}} a la main.',
    invalidCredentials: 'Identifiant de connexion ou mot de passe incorrect.',
    tooManyAttempts: 'Trop de tentatives : réessayez dans quelques minutes.',
    workstationNameTaken: 'Un poste porte déjà le nom {{name}}.',
    unknownSite: 'Ce site n’existe pas.',
  },
} as const;

type Widen<T> = { readonly [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };

/** Forme que tout catalogue de langue doit avoir : les mêmes clés que le français. */
export type LabelCatalog = Widen<typeof fr>;
