/**
 * Libellés français, langue par défaut (RG-EXI-054). Les textes suivent le glossaire ;
 * aucun libellé n'est écrit en dur dans un écran (fiche 0025, règle 4).
 */
export const fr = {
  application: {
    name: 'Cairn WMS',
  },
  shell: {
    home: 'Accueil',
    dismiss: 'Masquer',
  },
  navigation: {
    office: 'Bureau',
    receptions: 'Réceptions',
  },
  expectedReceipt: {
    openList: 'Attendus ouverts',
    create: 'Saisir un attendu',
    newTitle: 'Nouvel attendu',
    title: 'Attendu {{number}}',
    number: 'Attendu',
    principal: 'Donneur d’ordre',
    supplier: 'Fournisseur',
    expectedArrivalDate: 'Arrivée prévue',
    lineCount: 'Lignes',
    state: 'État',
    states: { open: 'Ouvert', settled: 'Soldé', cancelled: 'Annulé' },
    lines: 'Lignes de l’attendu',
    item: 'Référence',
    shortLabel: 'Libellé',
    quantity: 'Quantité',
    expectedQuantity: 'Attendu',
    servedQuantity: 'Servi',
    remainingQuantity: 'Solde',
    addLine: 'Ajouter une ligne',
    removeLine: 'Retirer la ligne',
    save: 'Enregistrer l’attendu',
    choose: 'Choisir…',
    none: 'Aucun attendu ouvert sur ce site.',
  },
  dock: {
    list: 'Quais',
    title: 'Quai {{code}}',
    free: 'Libre',
    occupied: 'Occupé',
    noVehicle: 'Aucun véhicule',
    arrival: 'Arrivage · {{vehicle}}',
    openedBy: 'Ouvert par {{name}} à {{time}}',
    occupiedSince: 'Occupé depuis',
  },
  arrival: {
    open: 'Ouvrir un arrivage',
    title: 'Nouvel arrivage au quai {{code}}',
    vehicle: 'Véhicule',
    carrier: 'Transporteur',
    noCarrier: 'Sans transporteur',
    submit: 'Ouvrir l’arrivage',
    cancel: 'Annuler',
  },
  common: {
    save: 'Enregistrer',
    cancel: 'Annuler',
    add: 'Ajouter',
    remove: 'Retirer',
    edit: 'Modifier',
    create: 'Créer',
    activate: 'Activer',
    deactivate: 'Désactiver',
    active: 'Actif',
    inactive: 'Inactif',
    none: 'Aucun',
    saved: 'Enregistré.',
    yes: 'Oui',
    no: 'Non',
  },
  administration: {
    group: 'Administration',
    settings: 'Paramétrage',
    usersAndTeams: 'Utilisateurs et équipes',
    principals: 'Donneurs d’ordre',
    sites: 'Sites',
    numbering: 'Numérotation',
    provider: 'Prestataire',
    workstations: 'Postes',
    users: 'Utilisateurs',
    roles: 'Rôles',
    teams: 'Équipes',
    remaining: 'Reste à solder : {{detail}}.',
  },
  site: {
    create: 'Créer un site',
    newTitle: 'Nouveau site',
    title: 'Site {{code}}',
    code: 'Code',
    name: 'Libellé',
    city: 'Ville',
    zoneCount: 'Zones',
    state: 'État',
    timeZone: 'Fuseau horaire',
    addressLine1: 'Adresse',
    addressLine2: 'Complément d’adresse',
    postalCode: 'Code postal',
    countryCode: 'Pays',
    codeLocked: 'Le code ne change plus : le site a déjà servi.',
    activation: 'Activation',
    missing: 'Pour activer le site, il manque : {{missing}}.',
    missingAddress: 'une adresse',
    missingZone: 'une zone active',
    ready: 'Le site peut être activé.',
    calendar: 'Calendrier',
    calendarEmpty:
      'Sans plage d’ouverture, le site est réputé ouvert en continu : les délais n’y sont pas qualifiés.',
    opensAt: 'Ouverture',
    closesAt: 'Fermeture',
    addRange: 'Ajouter une plage',
    closed: 'Fermé',
    closures: 'Jours fériés et fermetures',
    day: 'Date',
    label: 'Motif',
    kind: 'Nature',
    kinds: { publicHoliday: 'Jour férié', exceptional: 'Fermeture exceptionnelle' },
    addClosure: 'Ajouter une fermeture',
    addPublicHolidays: 'Ajouter les jours fériés de {{year}}',
    noClosure: 'Aucun jour fermé.',
    zones: 'Zones',
    addZone: 'Ajouter une zone',
    noZone: 'Aucune zone : ajoutez-en une pour pouvoir activer le site.',
    purpose: 'Vocation',
    cohabitation: 'Cohabitation',
    reservedFor: 'Donneur d’ordre réservataire',
    list: 'Sites',
  },
  weekday: {
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
  },
  zonePurpose: {
    storage: 'Stockage',
    picking: 'Prélèvement',
    receiving: 'Réception',
    shipping: 'Expédition',
    preparation: 'Préparation',
    consolidation: 'Consolidation',
    quarantine: 'Quarantaine',
    dispute: 'Litige',
    workshop: 'Atelier',
    destruction: 'Destruction',
    virtual: 'Virtuel',
  },
  cohabitation: { single: 'Mono-donneur d’ordre', shared: 'Mutualisée' },
  principalAdmin: {
    list: 'Donneurs d’ordre',
    create: 'Créer un donneur d’ordre',
    newTitle: 'Nouveau donneur d’ordre',
    code: 'Code',
    name: 'Libellé',
    group: 'Groupe',
    internal: 'Interne',
    email: 'Adresse électronique',
    phone: 'Téléphone',
    state: 'État',
    address: 'Coordonnées',
  },
  role: {
    list: 'Rôles',
    create: 'Composer un rôle',
    newTitle: 'Nouveau rôle',
    name: 'Libellé',
    nature: 'Nature',
    natures: { operational: 'Opérationnelle', administrative: 'Administrative' },
    natureHint:
      'Opérationnel, un rôle transmet à l’encadrant ses droits d’exécution ; administratif, il ne transmet que la visibilité.',
    template: 'Modèle',
    holders: 'Porteurs',
    permissions: 'Permissions',
    heldBy: 'Ce rôle est porté par {{count}} utilisateur(s) : la modification vaut pour chacun.',
    delete: 'Supprimer le rôle',
  },
  permissionDomain: { reception: 'Réception', settings: 'Paramétrage' },
  permission: {
    createExpectedReceipt: 'Saisir un attendu',
    openInboundArrival: 'Ouvrir un arrivage',
    administerProvider: 'Administrer le prestataire',
    administerSites: 'Administrer les sites, calendriers et zones',
    administerPrincipals: 'Administrer les donneurs d’ordre',
    administerRoles: 'Composer les rôles',
    administerUsers: 'Administrer les utilisateurs',
    administerExecutionSites: 'Fixer les sites d’exécution',
    administerTeams: 'Administrer les équipes',
    administerNumbering: 'Composer la numérotation',
    declareWorkstation: 'Déclarer et révoquer les postes',
  },
  user: {
    list: 'Utilisateurs',
    create: 'Créer un utilisateur',
    newTitle: 'Nouvel utilisateur',
    identity: 'Identité',
    displayName: 'Nom',
    loginName: 'Identifiant de connexion',
    email: 'Adresse électronique',
    password: 'Mot de passe',
    passwordHint: 'Douze caractères au moins. À la modification, laissez vide pour garder l’actuel.',
    roles: 'Rôles',
    sites: 'Sites',
    team: 'Équipe',
    reportsTo: 'Relève de',
    executionSites: 'Sites d’exécution',
    executionHint: 'Parmi ses sites, ceux où il agit ; ailleurs il consulte.',
    ownExecution: 'Nul ne modifie ses propres sites d’exécution.',
    restrictions: 'Restrictions par donneur d’ordre',
    restrictionsHint:
      'Exception : sans restriction, l’utilisateur voit tous les donneurs d’ordre de ses sites.',
    effectivePermissions: 'Permissions effectives',
    state: 'État',
    noSiteWarning: 'Rattaché à aucun site, cet utilisateur ne voit aucune donnée opérationnelle.',
  },
  team: {
    list: 'Équipes',
    create: 'Créer une équipe',
    newTitle: 'Nouvelle équipe',
    name: 'Nom',
    site: 'Site',
    lead: 'Encadrant',
    noLead: 'Sans encadrant',
    members: 'Membres',
    state: 'État',
  },
  numbering: {
    list: 'Schémas de numérotation',
    objectType: 'Type d’objet',
    composition: 'Composition',
    example: 'Exemple',
    segment: 'Segment',
    width: 'Chiffres',
    value: 'Texte',
    addSegment: 'Ajouter un segment',
    kinds: {
      literal: 'Texte fixe',
      site: 'Code site',
      principal: 'Code donneur d’ordre',
      year: 'Année',
      month: 'Mois',
      counter: 'Compteur',
    },
    problems: {
      leadingLiteralRequired: 'Le schéma commence par un texte fixe, qui dit le type d’objet.',
      leadingLiteralTaken: 'Ce texte de tête est déjà celui d’un autre type d’objet, ou le préfixe.',
      singleCounterRequired: 'Le schéma porte un compteur, un seul.',
      yearRequiredForMonth: 'Le mois s’accompagne de l’année.',
      separatorRequired: 'Deux codes de longueur variable se séparent par un texte fixe.',
    },
    objectTypes: { ExpectedReceipt: 'Attendu' },
  },
  provider: {
    title: 'Prestataire',
    name: 'Nom du prestataire',
    unnamed: 'Le prestataire n’a pas encore de nom.',
  },
  workstationAdmin: {
    list: 'Postes déclarés',
    name: 'Nom du poste',
    site: 'Site',
    state: 'État',
    revoked: 'Révoqué',
    revoke: 'Révoquer',
    declare: 'Déclarer ce navigateur comme poste',
    declareTitle: 'Ce navigateur',
    current: 'Ce navigateur est le poste « {{name}} ».',
    undeclared: 'Ce navigateur n’est pas un poste déclaré : aucun geste n’y est possible.',
  },
  siteSelector: { label: 'Site' },
  remainingKind: { expectedReceipts: 'attendu(s) ouvert(s)', inboundArrivals: 'arrivage(s) en cours' },
  session: {
    title: 'Ouvrir une session',
    loginName: 'Identifiant de connexion',
    password: 'Mot de passe',
    open: 'Ouvrir la session',
    close: 'Fermer la session',
  },
  workstation: {
    label: 'Poste',
    undeclared: 'Poste non déclaré',
  },
  failure: {
    noResponse:
      'Le serveur ne répond pas. Vérifiez la connexion, puis recommencez : rien ne sera enregistré deux fois.',
  },
  refusal: {
    unknownWorkstation: 'Ce poste n’existe pas.',
    codeTaken: 'Ce code est déjà employé.',
    codeLocked: 'Le code ne change plus : le site a déjà servi.',
    unknownTimeZone: 'Ce fuseau horaire n’existe pas.',
    activationIncomplete: 'Le site ne peut pas encore être activé : il lui manque une adresse ou une zone.',
    activityRemaining: 'Il reste du stock ou des flux en cours à solder.',
    overlappingRanges:
      'Deux plages d’ouverture d’un même jour se chevauchent, ou une plage ferme avant d’ouvrir.',
    unknownZone: 'Cette zone n’existe pas.',
    principalRequired: 'Une zone mono-donneur d’ordre désigne son donneur d’ordre réservataire.',
    foreignStock: 'La zone porte du stock d’un autre donneur d’ordre : elle ne peut pas lui être réservée.',
    internalPrincipal: 'Le donneur d’ordre interne ne se désactive pas.',
    unknownRole: 'Ce rôle n’existe pas.',
    nameTaken: 'Ce nom est déjà employé.',
    lastRoleAdministrator: 'Au moins un utilisateur actif doit garder l’administration des rôles.',
    roleHeld: 'Ce rôle est encore porté par des utilisateurs.',
    unknownUser: 'Cet utilisateur n’existe pas.',
    loginNameTaken: 'Cet identifiant de connexion est déjà employé.',
    passwordRequired: 'Un nouvel utilisateur reçoit un mot de passe.',
    unknownTeam: 'Cette équipe n’existe pas ou n’est plus active.',
    teamOutsideSites: 'L’équipe appartient à un site où l’utilisateur n’est pas rattaché.',
    hierarchyCycle: 'Ce rattachement placerait l’utilisateur sous quelqu’un qu’il encadre.',
    siteRequired: 'Un utilisateur s’active avec au moins un site.',
    ownExecutionSites: 'Nul ne modifie ses propres sites d’exécution.',
    executionOutsideSites: 'Un site d’exécution est choisi parmi les sites de rattachement.',
    leadOutsideSite: 'L’encadrant n’est pas rattaché au site de l’équipe.',
    teamHasMembers: 'L’équipe a encore des membres : replacez-les avant de la désactiver.',
    unknownObjectType: 'Ce type d’objet n’a pas de schéma de numérotation.',
    numberingNotUnique: 'Cette composition ne garantit pas l’unicité des identifiants.',
    unknownDock: 'Ce quai n’existe pas ou n’est plus actif.',
    dockOccupied: 'Le quai {{dock}} est déjà occupé par un véhicule.',
    unknownCarrier: 'Ce transporteur n’existe pas ou n’est plus actif.',
    unknownPrincipal: 'Ce donneur d’ordre n’existe pas ou n’est plus actif.',
    unknownSupplier: 'Ce fournisseur n’appartient pas au donneur d’ordre, ou n’est plus actif.',
    unknownItem: 'Une référence n’appartient pas au donneur d’ordre, ou ne peut plus être reçue.',
    duplicateItem: 'Une référence figure sur deux lignes.',
    invalidInput: 'La saisie est incomplète ou invalide.',
    notAuthenticated: 'Vous devez vous connecter.',
    permissionDenied: 'Vous n’avez pas la permission de faire ce geste.',
    outOfScope: 'Cet objet est hors de votre périmètre.',
    undeclaredWorkstation: 'Ce poste n’est pas déclaré : aucun geste n’est possible.',
    editLockHeldByOther: '{{holder}} a la main.',
    invalidCredentials: 'Identifiant de connexion ou mot de passe incorrect.',
    tooManyAttempts: 'Trop de tentatives : réessayez dans quelques minutes.',
    workstationNameTaken: 'Un poste porte déjà le nom {{name}}.',
    unknownSite: 'Ce site n’existe pas.',
  },
} as const;

type Widen<T> = { readonly [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };

/** Forme que tout catalogue de langue doit avoir : les mêmes clés que le français. */
export type LabelCatalog = Widen<typeof fr>;
